var lang = {
    tier: "Tầng",
    next_level: "Cấp tiếp theo",
    current_level_point: "Points allocated in this tier",
    skill_points: "Điểm kỹ năng",
    book_points: "Điểm thiên thư",
    require: "<p>Điều kiện:<br />Cấp độ nhân vật >= <strong>%d</strong><br />",
    reach: " đạt cấp >= ",
    skill_level: "",
    require_prev_level: "Skill points spent in previous tier ",
    default_char: "Mặc định",
    reborn_char: "Thăng Thiên",
    player_level: "Level >=",
    link: "Copy link build",
    arden: "Liệt Sơn",
    barbe: "Thần Hoàng",
    balo: "Cửu Lê",
    jadeon: "Thanh Vân Môn",
    modo: "Quỷ Đạo",
    skysong: "Thiên Âm Tự",
    lupin: "Hợp Hoan Phái",
    vim: "Quỷ Vương Tông",
    rayan: "Hoài Quang",
    celan: "Thiên Hoa",
    forta: "Thái Hạo",
    incense: "Phần Hương Cốc",
    kytos: "Anh Chiêu",
    psychea: "Khiên Cơ",
    hydran: "Phá Quân",
    seira: "Thanh La",
    gevrin: "Quy Vân",
    sylia: "Hoạ Ảnh",
    chroma: "Nguyên thần",
    chroma_skills: "Điểm kỹ năng bổ sung",
    skill: "Skill",
    select_skill: "select skill",
    descr: "Small description",
    found_error: "Found an error?",
    send: "Send",
    thankyou: "Thank you. To send another bug please click here again",
    writeanerror:
        "If you are reporting some error in skill, please write down some stats for this skill. At least for your current level. It will help to correct this error much faster.",
};
