var st = {
    t7: "Bảng 1",
    t8: "Bảng 2",
    t9: "Bảng 3",
    5373: {
        n: "Extreme Heat",
        d: "<span style='color:#ffffff'>Extreme Heat </span><span style='color:#11ff11'> <Blade> </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Ten suns gradually rise, causing unbearable heat<br /> The 1st of the Hydran Techniques, this multi-hit Combat Skill can be cast 3 times in 5 giây.<br /> </span><span style='color:#11ff11'>Single-target Attack, effective within </span><span style='color:#ffcb4a'>11 </span><span style='color:#11ff11'>meters<br /> </span><span style='color:#11ff11'></span><span style='color:#ff00ff'>Blade Soul: </span><span style='color:#11ff11'>When this skill reaches LV5, it has a 25%% chance to reduce the target's defence by 5%%<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>0.8 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>.<br /> </span><span style='color:#ff2222'>Combo: </span><span style='color:#ffcb4a;'>Cast skill within the allotted time to <br /> continue Combo.</span>",
    },
    5376: {
        n: "Golden Seal",
        d: "<span style='color:#ffffff'>Golden Seal </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>The style makes the man.<br /> Hydran Monster Slaying skill, particularly effective against early mosters.<br /> </span><span style='color:#11ff11'>Single-target Attack </span><span style='color:#ffcb4a'>11 </span><span style='color:#11ff11'>meters<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.2 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>.<br /> When Kill Streak reaches </span><span style='color:#ffcb4a'>3</span><span style='color:#ffffff'>, deals extra damage equal to </span><span style='color:#ffcb4a'>60%%</span><span style='color:#ffffff'> of Attack Power.<br /> (effectiveness reduced after you reach LV</span><span style='color:#ffcb4a'>60</span><span style='color:#ffffff'>)<br /> </span><span style='color:#ff2222'>Streak System: </span><span style='color:#ffcb4a;'>After you kill a monster, you have 60 giâys to kill another monster <br /> of the same type to continue your Kill Streak. Your Streak will be reset if you die<br />  or log off. Max Combo is equal to Skill Accuracy or 100, whichever is higher.</span>",
    },
    5379: {
        n: "Drifting Echo",
        d: "<span style='color:#ffffff'>Drifting Echo </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Watching this performance is like seeing the clouds playing around the bright moon, or flowers of snow floating through the wind.<br /> Hydran speed boost skill, increases Movement Speed.<br /> </span><span style='color:#11ff11'>Chúc phúc bản thân <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>0.8 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> For</span><span style='color:#ffcb4a'> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys, increases Movement Speed by </span><span style='color:#ffcb4a'>%.1f</span><span style='color:#ffffff;'> y/s.</span>",
    },
    5382: {
        n: "Red Sky Chant",
        d: "<span style='color:#ffffff'>Red Sky Chant </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>As gorgeous as the sunshine, as round as the earrings.<br /> Hydran tactical skill, reduces opponent's Resistance.<br /> </span><span style='color:#11ff11'>Single-target Attack, effective within </span><span style='color:#ffcb4a'>11 </span><span style='color:#11ff11'>meters<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.5 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>. Reduces<br /> target's Weaken RES </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> points for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    5374: {
        n: "Red Waves in the Cloud",
        d: "<span style='color:#ffffff'>Red Waves in the Cloud </span><span style='color:#11ff11'> <Axe> </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Clouds fold around the mountain<br /> The 2nd of the Hydran Techniques, this multi-hit Combat Skill can be cast 3 times in 5 giây.<br /> </span><span style='color:#11ff11'>Single-target Attack </span><span style='color:#ffcb4a'>7 </span><span style='color:#11ff11'>meters<br /> </span><span style='color:#11ff11'></span><span style='color:#ff00ff'>Axe Soul: </span><span style='color:#11ff11'>When this skill reaches LV5, it has a 25%% chance to paralyze the target for 2 giây.<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.5 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5377: {
        n: "White Fish in the Wave",
        d: "<span style='color:#ffffff'>White Fish in the Wave </span><span style='color:#11ff11'> <Spike> </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>The swallow flys across the clouds, the porpoise writhes in the sea.<br /> The 4th of the Hydran techniques, this multi-hit Combat Skill can be cast 3 times in 5 giây.<br /> </span><span style='color:#11ff11'>Single-target Attack </span><span style='color:#ffcb4a'>4 </span><span style='color:#11ff11'>meters<br /> </span><span style='color:#11ff11'></span><span style='color:#ff00ff'>Spike Soul: </span><span style='color:#11ff11'>When this skill reaches LV5, it has a 25%% chance to slow the target for </span><span style='color:#11ff11'>6giâys by 20%%.<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>0.5 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5380: {
        n: "Clouds Cover Mountain",
        d: "<span style='color:#ffffff'>Clouds Cover Mountain </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Waves lapping boulders, the clouds lie above the mountains.<br /> Hydran body training skill, increases Attack Power.<br /> </span><span style='color:#11ff11'>Bị động<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Bị độngly increases Attack Power by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>. Attack Power will be <br /> increased by your current Streak multiplied by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>, lasts for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    5383: {
        n: "Piercing Bolt",
        d: "<span style='color:#ffffff'>Piercing Bolt </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>The blade reflects the cool light. The cutting edge is hidden which takes the enemy by surprise.<br /> One tactical skill of Hydran. Marks the target.<br /> </span><span style='color:#11ff11'><Crossbow>Single-targeting Curse </span><span style='color:#ffcb4a'>28 </span><span style='color:#11ff11'> meters<br /> </span><span style='color:#11aaff;'>Right click the skill icon to check which Tome Spirit affect this skill.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Thời gian thi triển: </span><span style='color:#ffcb4a'>1.0 </span><span style='color:#ffffff'> giây.<br /> </span><span style='color:#ffffff'>Spirit Cost: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> giâys <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Marks a single target and increases the Critical Hit Rate against target by </span><span style='color:#ffcb4a'>%.1f%%</span><span style='color:#ffffff'>. The effect lasts<br /> </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    5375: {
        n: "Autumn Reeds",
        d: "<span style='color:#ffffff'>Autumn Reeds </span><span style='color:#11ff11'> <Crossbow> </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Brisk and harmonious lotus, tranquil.<br /> The 3rd of the Hydran techniques, this multi-hit Combat Skill can be cast 3 times in 5 giây.<br /> </span><span style='color:#11ff11'>Single-target Attack </span><span style='color:#ffcb4a'>18 </span><span style='color:#11ff11'>meters<br /> </span><span style='color:#11ff11'> </span><span style='color:#ff00ff'>Crossbow Soul: </span><span style='color:#11ff11'>When this skill reaches LV5, it has a 25%% chance to increase Attack Power 5%% for 6 giây.<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.0 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5378: {
        n: "Clouds at Sunset",
        d: "<span style='color:#ffffff'>Clouds at Sunset </span><span style='color:#11ff11'> <Drill> </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Sleepless in such a cold, I go outdoors to watch the night sky.<br /> The 5th of the Hydran techniques, this multi-hit Combat Skill can be cast 3 times in 5 giây.<br /> </span><span style='color:#11ff11'>Single-target Attack </span><span style='color:#ffcb4a'>14 </span><span style='color:#11ff11'>meters<br /> </span><span style='color:#11ff11'></span><span style='color:#ff00ff'>Drill Soul: </span><span style='color:#11ff11'>When this skill reaches LV5, it has a 25%% chance to </span><span style='color:#11ff11'>absorb Spirit from the target equal to 1%% of your Attack Power.<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.2 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5381: {
        n: "Endless Desert",
        d: "<span style='color:#ffffff'>Endless Desert </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>The Horse-Riding River, the Snow Land and the Endless Desert<br /> Hydran training skill, increases Resistance.<br /> </span><span style='color:#11ff11'>Bị động<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Bị độngly increases Silence RES by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> during Kill Streaks.</span>",
    },
    5384: {
        n: "Moonshot",
        d: "<span style='color:#ffffff'>Moonshot </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Sand explodes like hoarfrost, heard for miles.<br /> Hydran movement skill, dash attack.<br /> </span><span style='color:#11ff11'>Axe damage target in line </span><span style='color:#ffcb4a'>%d </span><span style='color:#11ff11'>meters<br /> </span><span style='color:#11ff11'>Weapon Requirement: Halberd</span><span style='color:#ffffff'><br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Instant Cast<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Leap forward </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> meters, dealing damage along the path.<br /> Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5385: {
        n: "Timber Token",
        d: "<span style='color:#ffffff'>Timber Token </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Imminent danger is approaching.<br /> Advanced Hydran Skill for monster slaying, dealing extra damage with Kill Streaks.<br /> </span><span style='color:#11ff11'>Axe Single-target Attack Range: </span><span style='color:#ffcb4a'>11 </span><span style='color:#11ff11'> meters<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.2 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Deals damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>. Deals bonus damage <br /> equal to </span><span style='color:#ffcb4a'>10 </span><span style='color:#ffffff'>times Kill Streak count. When Kill Streak has reached </span><span style='color:#ffcb4a'>30</span><span style='color:#ffffff'>, casting <br /> this Skill will grant extra Crit Damage of </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>and reset your Kill Streak.</span>",
    },
    5388: {
        n: "Emperor's Battlecry",
        d: "<span style='color:#ffffff'>Emperor's Battlecry </span><span style='color:#11ff11'><Blade> </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Great feats cannot be achieved without hard work.<br /> The 1st of the Hydran Ancient techniques.<br /> </span><span style='color:#11ff11'>Single-target Attack: </span><span style='color:#ffcb4a'>11 </span><span style='color:#11ff11'> yards. Can be cast </span><span style='color:#ffcb4a'>%d </span><span style='color:#11ff11'>times in 6 giây.<br /> </span><span style='color:#ff00ff'>Essense of the Blade <br /> When </span><span style='color:#11ff11'></span><span style='color:#ffcb4a'>Emperor's Battlecry </span><span style='color:#11ff11'>reaches Lv6, each strike has a </span><span style='color:#11ff11'>25%% chance </span><span style='color:#11ff11'>to lower the target's <br /> Defense by 5%%. Each cast increases the chance by 5%%. This effect can stack.<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>0.8 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5391: {
        n: "The Depth of Ocean",
        d: "<span style='color:#ffffff'>The Depth of Ocean </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>An ocean never refuses a river.<br /> A training skill, raising Max HP.<br /> </span><span style='color:#11ff11'>Bị động<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Raises Max HP by </span><span style='color:#ffcb4a'>%.1f</span><span style='color:#ffffff;'> times Base Defense.</span>",
    },
    5386: {
        n: "Wavedancer",
        d: "<span style='color:#ffffff'>Wavedancer </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>A swift and elegant dance over the waves.<br /> Hydran movement skill, teleports the caster to the target.<br /> </span><span style='color:#11ff11'>Chúc phúc bản thân <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Thời gian thi triển: </span><span style='color:#ffcb4a'>0.1 </span><span style='color:#ffffff'> giâys<br /> </span><span style='color:#ffffff'>Spirit Cost: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> giâys <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Instantly moves to the location where the marked target stands and increases your Stun Resistance by<br /> </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>. Duration: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. When there is no marked target, you can't instantly move.<br /> </span><span style='color:#ff00ff'>Effective Range: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'></span><span style='color:#ff00ff;'> meters.</span>",
    },
    5389: {
        n: "Heavy Snow at the Gate",
        d: "<span style='color:#ffffff'>Heavy Snow at the Gate </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>This place is ice-cold, and far your hometown.<br /> Hydran training skill, increases Attack Power<br /> </span><span style='color:#11ff11'>Bị động<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Bị độngly increases Attack Power </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> points.</span>",
    },
    5392: {
        n: "Hall of Sparrows",
        d: "<span style='color:#ffffff'>Hall of Sparrows </span><span style='color:#11ff11'><Cross Bow> </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Birds are flying and streams are flowing.<br /> The 3rd of the Hydran Ancient techniques.<br /> </span><span style='color:#11ff11'>Single-target Attack: </span><span style='color:#ffcb4a'>18 </span><span style='color:#11ff11'>yards. Can be cast </span><span style='color:#ffcb4a'>%d </span><span style='color:#11ff11'>times in 6 giây.<br /> </span><span style='color:#ff00ff'>Essense of the Cross Bow<br /> When </span><span style='color:#11ff11'>Hall of Sparrows</span><span style='color:#ffcb4a'> </span><span style='color:#11ff11'>reaches Lv6, each strike has a </span><span style='color:#11ff11'>25%% chance to gain <br /> Attack boost of 5%%. Each cast increases the chance by 5%%. This effect can stack.<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.0 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5387: {
        n: "Impervious",
        d: "<span style='color:#ffffff'>Impervious </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Lone Guardian.<br /> Hydran movement skill, deflects incoming damage.<br /> </span><span style='color:#11ff11'>Chúc phúc bản thân<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Thời gian thi triển: </span><span style='color:#ffcb4a'>0.5 </span><span style='color:#ffffff'> giâys<br /> </span><span style='color:#ffffff'>Spirit Cost: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> giâys <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Lifts the blade to block the attack, reducing the incoming damage by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> and grants immunity to<br /> all harmful effects, lasts </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    5390: {
        n: "Gentle Touch of Blue Jade",
        d: "<span style='color:#ffffff'>Gentle Touch of Blue Jade </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>The bright sun warms the Blue Jade.<br /> A Hydran training skill, raises Base Defense.<br /> </span><span style='color:#11ff11'>Bị động<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Raises Defense Bị độngly by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>.</span>",
    },
    5393: {
        n: "Crossed Streams",
        d: "<span style='color:#ffffff'>Crossed Streams </span><span style='color:#11ff11'><Axe> </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>When there's something strange...<br /> The 2nd of the Hydran Ancient techniques.<br /> </span><span style='color:#11ff11'>Single-target Attack Range: </span><span style='color:#ffcb4a'>7 </span><span style='color:#11ff11'>yards, can be cast </span><span style='color:#ffcb4a'>%d </span><span style='color:#11ff11'>times in 6 giây.<br /> </span><span style='color:#ff00ff'>Essense of the Broadsword<br /> When </span><span style='color:#11ff11'>Crossed Streams </span><span style='color:#ffcb4a'> </span><span style='color:#11ff11'>reaches Lv6, each strike has a </span><span style='color:#11ff11'>25%% chance to grant Paralyze Immunity <br /> to the caster for %d giây. Each cast increases the chance by 5%%. This effect can stack after.<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.5 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5394: {
        n: "Earth Token",
        d: "<span style='color:#ffffff'>Earth Token </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Necessary force.<br /> Advanced Hydran monster slaying skill, a powerful finishing move.<br /> </span><span style='color:#11ff11'>Single-target Attack Range: </span><span style='color:#ffcb4a'>5 </span><span style='color:#11ff11'>yards<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.2 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Base Attack: </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>; Bonus Attack: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>, plus Damage equal to </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>times<br /> Kill Streak. When the count reaches multiples of </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>, this <br /> Skill grants bonus Damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'> of Base Attack</span>",
    },
    5397: {
        n: "Forested Mountains",
        d: "<span style='color:#ffffff'>Forested Mountains </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Get drunk at the mountain peak and forget all the meaningless things in the world.<br /> Hydran training skill, enhances Resistances during skill combos.<br /> </span><span style='color:#11ff11'>Bị động<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>At the </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>rd cast, the Weapon Matched Resistance is enhanced by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> points<br /> for </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây. Blade, Axe, Crossbow, Spike, and Drill correspond to<br /> Weaken, Stun, Charm, Paralyze, and Hypnotize in that order.</span>",
    },
    5400: {
        n: "The Universe",
        d: "<span style='color:#ffffff'>The Universe </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>It expands infinitely over time and space.<br /> Advanced Hydran enhancement skill, triggers Combo Buff.<br /> </span><span style='color:#11ff11'>Bị động<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Makes the last move of Team-Combos happen. Upon the </span><span style='color:#ffcb4a'>4</span><span style='color:#ffffff'>, </span><span style='color:#ffcb4a'>5</span><span style='color:#ffffff'> hit, provides </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to trigger Last Move again.<br /> </span><span style='color:#ff00ff'>Blade Last Move</span><span style='color:#ffcb4a'>: Adds 8%% Base Damage. In 1-%d giâys, the damage dealt to target increases by %d%%, AOE effect.<br /> </span><span style='color:#ff00ff'>Axeblade Last Move</span><span style='color:#ffcb4a'>: Adds 15%% Base Damage. Provides %d%% chance to stun the target for 1 to 4 giây.<br /> </span><span style='color:#ff00ff'>Crossbow Last Move</span><span style='color:#ffcb4a'>: Adds 10%% Base Damage. Provides %d%% chance to increase Critical Hit Rate by 5%% for 6 giây.<br /> </span><span style='color:#ff00ff'>Bayonet Last Move</span><span style='color:#ffcb4a'>:Adds 5%% Base Damage. Provides %d%% chance to freeze target for 1 to 3 giây.<br /> </span><span style='color:#ff00ff'>Awl Last Move</span><span style='color:#ffcb4a;'>: Adds 12%% Base Damage. The amount of Spirit the target loses is 10%%-%d%% of your current spirit amount.</span>",
    },
    5395: {
        n: "Shifting Constellation",
        d: "<span style='color:#ffffff'>Shifting Constellation </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Time passes, change happens.<br /> The 5th Hydran movement skill, an evasive backdash.<br /> </span><span style='color:#11ff11'>Chúc phúc bản thân <br /> </span><span style='color:#11ff11'>Weapon Requirement: Halberd</span><span style='color:#ffffff'><br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Thời gian thi triển: </span><span style='color:#ffcb4a'>0.3 </span><span style='color:#ffffff'>giây<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Distances the caster by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>yards.</span>",
    },
    5398: {
        n: "Footprints of the Past",
        d: "<span style='color:#ffffff'>Footprints of the Past </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Life is short and your footprints won't last.<br /> Advanced Hydran movement skill, swaps locations with target player.<br /> </span><span style='color:#11ff11'>Chúc phúc bản thân <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Thời gian thi triển: </span><span style='color:#ffcb4a'>0.1 </span><span style='color:#ffffff'> giâys<br /> </span><span style='color:#ffffff'>Spirit Cost: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> giâys <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Switches places with marked target. If the distance is more than </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> meters,<br /> the skill fails. Can't switch places when there is no marked target.</span>",
    },
    5401: {
        n: "Leaping Dragon",
        d: "<span style='color:#ffffff'>Leaping Dragon </span><span style='color:#11ff11'><Spike> </span><span style='color:#ffcb4a'>%s/6 <br /> </span><span style='color:#ffcb4a'>I expected Prince Charming, only to run into scum like you. <br /> The 4th Hydran Ancient technique. <br /> </span><span style='color:#11ff11'>Single-target Attack within </span><span style='color:#ffcb4a'>4 </span><span style='color:#11ff11'>yards, can be cast </span><span style='color:#ffcb4a'>%d </span><span style='color:#11ff11'> times in 6 giâys <br /> </span><span style='color:#ff00ff'>Essense of the Waistsword <br /> When </span><span style='color:#11ff11'></span><span style='color:#ffcb4a'>Leaping Dragon </span><span style='color:#11ff11'>reaches Lv6, each strike has a </span><span style='color:#11ff11'>25%% chance to Slow the <br /> target for </span><span style='color:#11ff11'>6 giâys by 20%%. Each cast increases the chance by 5%%. This effect can stack. <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>0.5 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5396: {
        n: "Luna Gale",
        d: "<span style='color:#ffffff'>Luna Gale </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Home is thousands of miles away, and the path is full of storms and deserts.<br /> Advanced Hydran movement skill, a damaging charge.<br /> </span><span style='color:#11ff11'>Deals Damage in a line of </span><span style='color:#ffcb4a'>%d </span><span style='color:#11ff11'>yards<br /> </span><span style='color:#11ff11'>Weapon Requirement: Halberd</span><span style='color:#ffffff'><br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Thời gian thi triển: </span><span style='color:#ffcb4a'>0.1 </span><span style='color:#ffffff'>giây<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Dash forward and deal damage along the path, with <br /> Base Attack of </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> and extra damage of </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>.<br /> Can be cast </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> times consecutively.</span>",
    },
    5399: {
        n: "Smokescreen",
        d: "<span style='color:#ffffff'>Smokescreen </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>There's no such thing as fighting dirty: there is only fighting.<br /> Advanced Hydran dueling skill, blinds nearby players.<br /> </span><span style='color:#11ff11'>Select Single-target Cast <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Thời gian thi triển: </span><span style='color:#ffcb4a'>0.1 </span><span style='color:#ffffff'> giâys<br /> </span><span style='color:#ffffff'>Spirit Cost: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> giâys <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Throws smoke grenade to the target area. The radius of the smoke is </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> meters.<br /> When the target enters into the smoke area, its visual field and attack are blocked, lasts </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây.<br /> and the target's speed is reduced by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5402: {
        n: "Three Great Changes",
        d: "<span style='color:#ffffff'>Three Great Changes </span><span style='color:#11ff11'><Awl> </span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Though it might take awhile to work itself out, everything is going to be fine again.<br /> Smasher's best weapon, useful Team-Combos skill.<br /> </span><span style='color:#11ff11'>Single-target attack </span><span style='color:#ffcb4a'>14 </span><span style='color:#11ff11'> meters Can attack in series </span><span style='color:#ffcb4a'>%d </span><span style='color:#11ff11'> times<br /> </span><span style='color:#ff00ff'>Awl Specialty<br /> </span><span style='color:#11ff11'></span><span style='color:#ffcb4a'>When Sundown Shadow reaches Level </span><span style='color:#11ff11'>5, provides </span><span style='color:#11ff11'>25%% chance to absorb target's Spirit, by<br /> 1%% of your Base Attack. Upon every hit, provides 5%% chance to trigger. And after 3 hits, the absorb amount increases by 1%%.<br /> </span><span style='color:#11aaff;'>Right click the skill icon to check which Tome Spirit affects this skill.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'> Cast Time </span><span style='color:#ffcb4a'>1.2 </span><span style='color:#ffffff'>giâys<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Deals extra Damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5403: {
        n: "Fire Token",
        d: "<span style='color:#ffffff'>Fire Token </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>No pleasure without pain.<br /> Advanced Hydran skill, can be cast 4 times in 6 giây.<br /> </span><span style='color:#11ff11'>Single-target Attack Range: </span><span style='color:#ffcb4a'>5 </span><span style='color:#11ff11'>meters <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>2.2 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Grants Base Attack equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power, and an extra </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'>of Base Attack <br /> plus </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>Skill Damage for each cast. The last cast provides a shield <br /> for </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giâys to block incoming damage equal to current Kill Streak count.</span>",
    },
    5406: {
        n: "Transposition Spell",
        d: "<span style='color:#ffffff'>Transposition Spell </span><span style='color:#ffcb4a'>%s/6 <br /> </span><span style='color:#ffcb4a'>Every change, no matter how different to the eyes, conforms to a sole principle. <br /> Advanced Hydran tactical skill, redirecting incoming damage. <br /> </span><span style='color:#11ff11'>Chúc phúc bản thân <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.5 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>This skill can only hit players affected by Piercing Bolt. Grants a(n) <br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance of diverting </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of skill damage from other players. <br /> Lasts </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây. <br /> </span><span style='color:#ff00ff;'>(Ineffective on monsters)</span>",
    },
    5409: {
        n: "Patsy",
        d: "<span style='color:#ffffff'>Patsy </span><span style='color:#ffcb4a'>%s/6 <br /> </span><span style='color:#ffcb4a'>Behind every great leader is a great scapegoat. <br /> Ultimate Hydran tactical skill, developed for team battles. <br /> </span><span style='color:#11ff11'>Single-target Attack, effective within </span><span style='color:#ffcb4a'>18 </span><span style='color:#11ff11'>meters. <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.0 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Single-target Attack with bonus Base Damage. The target takes on the caster's appearance, is <br /> unable to cast skills, and is targetable by friendly players. Duration: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây. <br /> (Ineffective against monsters)</span>",
    },
    5404: {
        n: "Dragonrest Shoal",
        d: "<span style='color:#ffffff'>Dragonrest Shoal </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Even a powerful dragon has weak moments.<br /> Advanced Hydran Movement skill that breaks control effects.<br /> </span><span style='color:#11ff11'>Chúc phúc bản thân: within a(n) </span><span style='color:#ffcb4a'>%d </span><span style='color:#11ff11'>giây duration, <br /> can be cast </span><span style='color:#ffcb4a'>%d</span><span style='color:#11ff11'> times </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>0.3 </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>When under the following Control Effects, casting this skill will have <br /> a </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'>chance to reduce Control Duration by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây, plus <br /> a </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'>chance to remove the Control Effect immediately. <br /> </span><span style='color:#11ff11;'>Applicable Control Effects: Paralyze, Stun, Charm, Hypnotize, Freeze, and Transform.</span>",
    },
    5407: {
        n: "The Fleeing Red Bird",
        d: "<span style='color:#ffffff'>The Fleeing Red Bird </span><span style='color:#ffcb4a'>%s/9 <br /> </span><span style='color:#ffcb4a'>A red bird flies under the sun as its shadow passes westward on the ground. <br /> Advanced Hydran combo skill, triggers hidden combo effects. <br /> </span><span style='color:#11ff11'>Bị động <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Grants multi-hit skills a </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'>chance to trigger the following effects at </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>hits: <br /> </span><span style='color:#ff00ff'>Blade: </span><span style='color:#ffcb4a'>For %.1f giâys, the next hit deals an additional </span><span style='color:#ffcb4a'>%d%% damage <br /> </span><span style='color:#ff00ff'>Axe: </span><span style='color:#ffcb4a'>Paralyze Immunity for %.1f giâys <br /> </span><span style='color:#ff00ff'>Crossbow: </span><span style='color:#ffcb4a'>For %.1f giâys, Skill Accuracy is increased by </span><span style='color:#ffcb4a'>%d points <br /> </span><span style='color:#ff00ff'>Spike: </span><span style='color:#ffcb4a'>For %.1f giâys, Crit Rate is increased by </span><span style='color:#ffcb4a'>%d%% <br /> </span><span style='color:#ff00ff'>Drill: </span><span style='color:#ffcb4a'>For %.1f giâys, speed is increased by </span><span style='color:#ffcb4a;'>%.1f m/s</span>",
    },
    5410: {
        n: "Moonfall",
        d: "<span style='color:#ffffff'>Moonfall </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>The moon fades and the stars scatter.<br /> 1st of the Hydran Team Tactics, rendering teammates fearless.<br /> </span><span style='color:#11ff11'>Crowd Blessing<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Thời gian thi triển: </span><span style='color:#ffcb4a'>1.4 </span><span style='color:#ffffff'> giây.<br /> </span><span style='color:#ffffff'>Spirit Cost: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> giâys <br /> </span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffffff'>Allies within </span><span style='color:#ffcb4a'>18</span><span style='color:#ffffff'> meters around you receive a Fearless Effect for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys, increasing their<br /> Skill Evasion against AOE attack by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> and granting them<br /> Block Effect to reduce incoming damage by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.<br /> (Block Effect is effective against extra damage)</span>",
    },
    5405: {
        n: "Reflection of Light and Shadow",
        d: "<span style='color:#ffffff'>Reflection of Light and Shadow </span><span style='color:#ffcb4a'>%s/5 <br /> </span><span style='color:#ffcb4a'>Reflections under a bright sun are a pleasant sight. <br /> Advanced Hydran movement skill that allows multiple backdashes. <br /> </span><span style='color:#11ff11'>Chúc phúc bản thân: </span><span style='color:#ffcb4a'>within a %d giây duration, can be cast </span><span style='color:#ffcb4a'>%d times <br /> </span><span style='color:#11ff11'>Weapon Requirement: Halberd</span><span style='color:#ffffff'> <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>0.3 </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Swiftly evade backwards after having mastered </span><span style='color:#ffcb4a'>Shifting Constellation </span><span style='color:#ffffff'>, <br /> for a distance related to the level of </span><span style='color:#ffcb4a'>Shifting Constellation</span><span style='color:#ffffff;'>.</span>",
    },
    5408: {
        n: "Warrior's Motivation",
        d: "<span style='color:#ffffff'>Warrior's Motivation </span><span style='color:#ffcb4a'>%s/6 <br /> </span><span style='color:#ffcb4a'>Hometown memories push you past your limits. <br /> Advanced Hydran combo skill, increases damage and Cast Limits. <br /> </span><span style='color:#11ff11'>Bị động <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Each cast of a multi-hit skill adds </span><span style='color:#ffcb4a'>%.1f%% </span><span style='color:#ffffff'>bonus damage. <br /> At Lv</span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>, multi-hit skills gain 1 additional hit.</span>",
    },
    5411: {
        n: "Seven Star Flash",
        d: "<span style='color:#ffffff'>Seven Star Flash </span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>On a clear autumn night, the stars are shining with stunning brilliance.<br /> 2nd of the Hydran Team Tactics, rendering teammates courageous.<br /> </span><span style='color:#11ff11'>Crowd Blessing <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.4 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Teammates within </span><span style='color:#ffcb4a'>18 </span><span style='color:#ffffff'>meters are granted the Assail buff for </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây. When teammates <br /> cast Single-target Skills, their Effective Attack Range will be extended by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>meters.</span>",
    },
    5412: {
        n: "Aquatic Seal",
        d: "<span style='color:#ffffff'>Aquatic Seal </span><span style='color:#11ff11'><Halberd> </span><span style='color:#ffcb4a'>%s/8 <br /> </span><span style='color:#ffcb4a'>The sign of disaster has not yet shown itself. <br /> Ultimate Hydran Monster Slaying skill, hits 3 times in a single cast. <br /> </span><span style='color:#11ff11'>AOE Attack Range: </span><span style='color:#ffcb4a'>5 </span><span style='color:#11ff11'>meters <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>2.1 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffffff'>Target limitation </span><span style='color:#ffcb4a'>6 </span><span style='color:#11ff11'> <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Deals Base Damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of attack power, and bonus Damage equal to </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'>of Base Attack <br /> plus </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>Skill Damage each hit. When Kill Streak count reaches a multiple of </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>, there will be a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'> <br /> chance to reset Skill Thời gian hồi kỹ năng.</span>",
    },
    5413: {
        n: "Celestial Majesty",
        d: "<span style='color:#ffffff'>Celestial Majesty </span><span style='color:#ffcb4a'>%s/4<br /> </span><span style='color:#ffcb4a'>The clouds keep shifting forms, even with nothing to gain.<br /> Ultimate Hydran tactical skill, for mob protection.<br /> </span><span style='color:#11ff11'>Single-target Curse<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.2 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Removes </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>negative effects and renders you invincible to everything <br /> but the target for </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây. <br /> If the target dies, the buff is cancelled.</span>",
    },
    5414: {
        n: "Cataclysmic Force",
        d: "<span style='color:#ffffff'>Cataclysmic Force </span><span style='color:#ffcb4a'>%s/4<br /> </span><span style='color:#ffcb4a'>The waters are raging while the soldiers are fighting.<br /> Ultimate Hydran combo enhancement, adding new strikes and untold efficiency to multi-hit skills.<br /> </span><span style='color:#11ff11'>Chúc phúc bản thân<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Cast Time </span><span style='color:#ffcb4a'>1.2 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Grants a Limit Break buff and Slow immunity for </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây. <br /> Multi-hit skills have no limit to the number of casts and the Connecting Window is extended by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây. <br /> Additionally, all multi-hit skills can trigger the Execution strike on the </span><span style='color:#ffcb4a'>6</span><span style='color:#ffffff'>th hit: <br /> </span><span style='color:#ff00ff'>Blade: </span><span style='color:#ffcb4a'>Adds 8%% Bonus Damage and has a chance to remove movement buffs <br /> </span><span style='color:#ff00ff'>Axe: </span><span style='color:#ffcb4a'>Adds 15%% Bonus Damage. If stunned, the target will take 50%% more Crit Damage for 8 giâys <br /> </span><span style='color:#ff00ff'>Crossbow: </span><span style='color:#ffcb4a'>Adds 10%% Bonus Damage. If stunned, the target will be 8%% more susceptible to Crits for 8 giâys <br /> </span><span style='color:#ff00ff'>Spike: </span><span style='color:#ffcb4a'>Adds 5%% Bonus Damage and removes 2 positive effects from the target <br /> </span><span style='color:#ff00ff'>Drill: </span><span style='color:#ffcb4a;'>Adds 12%% Bonus Damage. If the target's HP drops below 50%%, he/she will be charmed for 4 giâys</span>",
    },
    5415: {
        n: "Meteor Shower",
        d: "<span style='color:#ffffff'>Meteor Shower </span><span style='color:#11ff11'><Halberd> </span><span style='color:#ffcb4a'>%s/4 <br /> </span><span style='color:#ffcb4a'>Every year on this night, the sky becomes crystal clear and the stars shine through effortlessly. <br /> ffcb4aUltimate Hydran combat skill, with 6 powerful strikes in a single cast. <br /> </span><span style='color:#11ff11'>Single-target Attack, effective within </span><span style='color:#ffcb4a'>12 </span><span style='color:#11ff11'>meters <br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Thời gian thi triển: </span><span style='color:#ffcb4a'>2.5 </span><span style='color:#ffffff'>giâys <br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'> Spirit <br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây <br /> </span><span style='color:#ffcb4a'> <br /> </span><span style='color:#ffffff'>Base Attack Damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d. </span><span style='color:#ffffff'>Each hit has a(n) </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'>chance <br /> to apply a </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>giây debuff that increases Crit Damage dealt to the target by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>. <br /> If the effect stacks </span><span style='color:#ffcb4a'>5 </span><span style='color:#ffffff'>times, </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>positive effects will be removed from the target. <br /> %s</span>",
        p1: "<span style='color:#cc33ff'>Firmus - Arcane Charge<br /> </span><span style='color:#11ff11'>*</span><span style='color:#ffcb4a'>Execution Damage will rise with higher rank of Esper Skills</span><span style='color:#11ff11'>*<br /> </span><span style='color:#11ff11'>At Rank 5, each hit will deal bonus </span><span style='color:#ffcb4a'>10% </span><span style='color:#11ff11;'>damage and remove 1 positive effect on the target.</span>",
    },
    5447: {
        n: "Energy",
        d: "<span style='color:#3388ff'>Energy　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Every </span><span style='color:#ffcb4a'>1 </span><span style='color:#ffffff'>rank of Basic Hydran techniques increases Attack Power by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5448: {
        n: "Urh",
        d: "<span style='color:#3388ff'>Wudu Saint　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>When Kill Streak reaches </span><span style='color:#ffcb4a'>100</span><span style='color:#ffffff'>, </span><span style='color:#ffcb4a'>Golden Seal </span><span style='color:#ffffff'>increases Defense by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>points for </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5449: {
        n: "Lock of Jadeon",
        d: "<span style='color:#3388ff'>Great Secret　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Every </span><span style='color:#ffcb4a'>1 </span><span style='color:#ffffff'>rank of Basic Hydran techniques increases Defense by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5450: {
        n: "Tann",
        d: "<span style='color:#3388ff'>Tann　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động Effect<br /> </span><span style='color:#ffffff'>Shortens </span><span style='color:#ffcb4a'>Drifting Echo</span><span style='color:#ffffff'> Thời gian hồi kỹ năng by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>. In Berserker State, increases Acceleration by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5451: {
        n: "Sunbeam",
        d: "<span style='color:#3388ff'>Sunbeam　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>When Kill Streak reaches </span><span style='color:#ffcb4a'>100</span><span style='color:#ffffff'>, </span><span style='color:#ffcb4a'>Timber Token </span><span style='color:#ffffff'>increases Attack Power by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>for </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>seocnds.</span>",
    },
    5452: {
        n: "Skywise",
        d: "<span style='color:#3388ff'>Skywise　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>When Kill Streak increases by </span><span style='color:#ffcb4a'>1</span><span style='color:#ffffff'>, Attack Power rises by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>. Skills related:<br /> </span><span style='color:#ffcb4a;'>Golden Seal, Timber Token, Earth Token, Fire Token, Aquatic Seal</span>",
    },
    5453: {
        n: "Lyan",
        d: "<span style='color:#3388ff'>Lyan　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Reduces the Spirit cost of monster slaying skills by %d%%, and reduces the Thời gian hồi kỹ năng by %d giây.<br /> Related Skills:<br /> </span><span style='color:#ffcb4a;'>Golden Seal, Timber Token, Earth Token, Fire Token, Aquatic Seal</span>",
    },
    5454: {
        n: "Phul",
        d: "<span style='color:#3388ff'>Phul　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>For every </span><span style='color:#ffcb4a'>1 </span><span style='color:#ffffff'>rank of </span><span style='color:#ffcb4a'>The Depth of Ocean</span><span style='color:#ffffff'>, Combo Ultimate deals additional damage equal to </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff;'>of Max HP.</span>",
    },
    5455: {
        n: "Juen",
        d: "<span style='color:#3388ff'>Juen　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Monster slaying skills deal additional damage equal to </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'>of Attack Power.<br /> Related Skills:<br /> </span><span style='color:#ffcb4a;'>Golden Seal, Timber Token, Earth Token, Fire Token, Aquatic Seal</span>",
    },
    5456: {
        n: "Icemoon",
        d: "<span style='color:#3388ff'>Icemoon　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Every </span><span style='color:#ffcb4a'>3 </span><span style='color:#ffffff'>ranks of </span><span style='color:#ffcb4a'>Heavy Snow at the Gate </span><span style='color:#ffffff'>increases Attack Power by </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'> and CritStrike Rate by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5457: {
        n: "Duality",
        d: "<span style='color:#3388ff'>Duality　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Every </span><span style='color:#ffcb4a'>3 </span><span style='color:#ffffff'>ranks of </span><span style='color:#ffcb4a'>Gentle Touch of Blue Jade </span><span style='color:#ffffff'>increases Defense by </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'>and CritBonus by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5458: {
        n: "Cloudroof",
        d: "<span style='color:#3388ff'>Cloudroof　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Increases </span><span style='color:#ffcb4a'>Forested Mountains</span><span style='color:#ffffff'>' effect duration by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5459: {
        n: "Chish",
        d: "<span style='color:#3388ff'>Chish　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>When Kill Streak increases by </span><span style='color:#ffcb4a'>1</span><span style='color:#ffffff'>, </span><span style='color:#ffcb4a'>Fire Token</span><span style='color:#ffffff'>'s damage increases by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5460: {
        n: "Zozphur",
        d: "<span style='color:#3388ff'>Zozphur　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff;'>Fire Token's shield blocks %d%% more damage.</span>",
    },
    5461: {
        n: "Ubantez",
        d: "<span style='color:#3388ff'>Ubantez　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Increases the duration of </span><span style='color:#ffcb4a'>Forested Mountains</span><span style='color:#ffffff'>' effect by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5462: {
        n: "Sky Chief",
        d: "<span style='color:#3388ff'>Sky Chief　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Aquatic Seal </span><span style='color:#ffffff'>deals additional damage equal to </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff;'>of Attack Power.</span>",
    },
    5463: {
        n: "Meteor Axe",
        d: "<span style='color:#3388ff'>Meteor Axe　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Meteor Shower </span><span style='color:#ffffff'>has a </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff;'>chance to Thời gian hồi kỹ năng instantly.</span>",
    },
    5464: {
        n: "Ruling Star",
        d: "<span style='color:#3388ff'>Ruling Star　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>For every </span><span style='color:#ffcb4a'>1 </span><span style='color:#ffffff'>rank of </span><span style='color:#ffcb4a'>Clouds Cover Mountain</span><span style='color:#ffffff'>, the Combo II strike gains additional damage equal to your level multiplied by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    5465: {
        n: "Venn",
        d: "<span style='color:#3388ff'>Venn　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>For every </span><span style='color:#ffcb4a'>1 </span><span style='color:#ffffff'>rank of </span><span style='color:#ffcb4a'> Endless Desert</span><span style='color:#ffffff'>, the Combo Ultimate strike increases Silence RES by an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5466: {
        n: "Sky Stallion",
        d: "<span style='color:#3388ff'>Sky Stallion　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Hydran Ancient techniques deal additional damage per strike equal to </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff;'>of Attack Power.</span>",
    },
    5467: {
        n: "Lukom",
        d: "<span style='color:#3388ff'>Lukom　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Connecting Window of multi-hit skills is increased by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây(s).</span>",
    },
    5468: {
        n: "Linkzzar",
        d: "<span style='color:#3388ff'>Linkzzar　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Improves The Fleeing Red Bird's effects:<br /> </span><span style='color:#11aaff'>Blade </span><span style='color:#11aaff'>Mode - Duration increases by </span><span style='color:#ffcb4a'>%d </span><span style='color:#11aaff'>giâys, the damage of your next strike is increased by </span><span style='color:#ffcb4a'>%d%% <br /> </span><span style='color:#11aaff'>Axe </span><span style='color:#11aaff'>Mode - Duration increases by </span><span style='color:#ffcb4a'>%d </span><span style='color:#11aaff'>giâys, removes 1 negative effect<br /> </span><span style='color:#11aaff'>Crossbow </span><span style='color:#11aaff'>Mode Duration increases by </span><span style='color:#ffcb4a'>%d </span><span style='color:#11aaff'>giâys, Skill Accuracy increases by </span><span style='color:#ffcb4a'>%d</span><span style='color:#11aaff'> <br /> </span><span style='color:#11aaff'>Spike </span><span style='color:#11aaff'>Mode - Duration increases by </span><span style='color:#ffcb4a'>%d </span><span style='color:#11aaff'>giâys, Crit Rate increases by </span><span style='color:#ffcb4a'>%d%% <br /> </span><span style='color:#11aaff'>Drill </span><span style='color:#11aaff'>Mode - Duration increases by </span><span style='color:#ffcb4a'>%d </span><span style='color:#11aaff;'>giâys, removes Slow Effect</span>",
    },
    5469: {
        n: "Honpyra",
        d: "<span style='color:#3388ff'>Honpyra　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Targets affected by </span><span style='color:#ffcb4a'>Smokescreen </span><span style='color:#ffffff'>are Slowed an additional </span><span style='color:#ffcb4a'>%d%%<br /> </span><span style='color:#ffffff'>for </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5470: {
        n: "Earthsplit",
        d: "<span style='color:#3388ff'>Earthsplit　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Increases the duration of </span><span style='color:#ffcb4a'>Smokescreen </span><span style='color:#ffffff'>by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5471: {
        n: "Calamity",
        d: "<span style='color:#3388ff'>Calamity　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>The Universe</span><span style='color:#ffffff'>'s chance to activate the Combo Buff is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5472: {
        n: "Keyan",
        d: "<span style='color:#3388ff'>Keyan　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động Effect<br /> </span><span style='color:#ffffff'>Every time you learn </span><span style='color:#ffcb4a'>3</span><span style='color:#ffffff'> level of </span><span style='color:#ffcb4a'>Fluting Echoes</span><span style='color:#ffffff'>, character's Base Critical Hit Rate increases by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> At the proper distance, the Critical Hit Rate of Weapon's Team-Combos increases by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> Blade: </span><span style='color:#ffcb4a'>7-11</span><span style='color:#ffffff'> meters; Axeblade: </span><span style='color:#ffcb4a'>4-7</span><span style='color:#ffffff'> meters; Crossbow: </span><span style='color:#ffcb4a'>14-18</span><span style='color:#ffffff'> meters; Bayonet: </span><span style='color:#ffcb4a'>0-4</span><span style='color:#ffffff'> meters; Awl: </span><span style='color:#ffcb4a'>11-14</span><span style='color:#ffffff;'> meters.</span>",
    },
    5473: {
        n: "Tuolo",
        d: "<span style='color:#3388ff'>Tuolo　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Reduces </span><span style='color:#ffcb4a'>Patsy</span><span style='color:#ffffff'>'s Thời gian hồi kỹ năng by </span><span style='color:#ffcb4a'>%d <br /> </span><span style='color:#ffffff'>giây. For every </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>points of Skill Accuracy more than that of the target, the duration increases by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5474: {
        n: "Dragonpool",
        d: "<span style='color:#3388ff'>Dragonpool　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Increases </span><span style='color:#ffcb4a'>Transposition Spell</span><span style='color:#ffffff'>'s chance of success by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5475: {
        n: "Phoenix Hall",
        d: "<span style='color:#3388ff'>Phoenix Hall　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>The duration of </span><span style='color:#ffcb4a'>Transposition Spell </span><span style='color:#ffffff'>is increased by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5476: {
        n: "Crimson Flight",
        d: "<span style='color:#3388ff'>Crimson Flight　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Moonfall</span><span style='color:#ffffff'>'s Fearless buff also reduces damage <br /> taken from AOE skills by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>. The duration is extended by </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff;'>of your Skill Evasion.</span>",
    },
    5477: {
        n: "Celestial Bliss",
        d: "<span style='color:#3388ff'>Celestial Bliss　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Increases the duration of</span><span style='color:#ffcb4a'> Moonfall </span><span style='color:#ffffff'>and </span><span style='color:#ffcb4a'>Seven Star Flash </span><span style='color:#ffffff'>by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5478: {
        n: "Lonestar",
        d: "<span style='color:#3388ff'>Lonestar　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Seven Star Flash</span><span style='color:#ffffff'>'s Assail Effect increases the <br /> range of Single-target Skills by an additional</span><span style='color:#ffcb4a'> %d</span><span style='color:#ffffff'> meters, and increases damage by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5479: {
        n: "Widow's Grief",
        d: "<span style='color:#3388ff'>Widow's Grief　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Extends the duration of </span><span style='color:#ffcb4a'>Cataclysmic Force </span><span style='color:#ffffff'>by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5480: {
        n: "Pestilence",
        d: "<span style='color:#3388ff'>Pestilence　</span><span style='color:#ffffff'>%s/1<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Meteor Shower </span><span style='color:#ffffff'>will be auto-cast after the </span><span style='color:#ffcb4a'>6</span><span style='color:#ffffff;'>th cast of a multi-hit skill.</span>",
    },
    5481: {
        n: "Shatter",
        d: "<span style='color:#3388ff'>Shatter　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Lowers </span><span style='color:#ffcb4a'>Piercing Bolt </span><span style='color:#ffffff'>Skill Thời gian hồi kỹ năng by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5482: {
        n: "Canopy",
        d: "<span style='color:#3388ff'>Canopy　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Extends </span><span style='color:#ffcb4a'>Piercing Bolt </span><span style='color:#ffffff'>Mark Duration by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5483: {
        n: "Heavenly Void",
        d: "<span style='color:#3388ff'>Heavenly Void　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Lowers </span><span style='color:#ffcb4a'>Wavedancer </span><span style='color:#ffffff'>Skill Thời gian hồi kỹ năng by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5484: {
        n: "Skywrath",
        d: "<span style='color:#3388ff'>Heavenly Force </span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Extends Skill Duration of </span><span style='color:#ffcb4a'>Impervious </span><span style='color:#ffffff'>by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5485: {
        n: "Trinity",
        d: "<span style='color:#3388ff'>Trinity　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'> <br /> </span><span style='color:#ffcb4a'>Bị động <br /> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Wavedancer</span><span style='color:#ffffff'> raises your Stun Resistance </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff'>points for </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5486: {
        n: "Eight Seats",
        d: "<span style='color:#3388ff'>Eight Seats　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'> <br /> </span><span style='color:#ffcb4a'>Bị động <br /> </span><span style='color:#ffffff'>Extends the range of </span><span style='color:#ffcb4a'>Wavedancer </span><span style='color:#ffffff'>by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>yards.</span>",
    },
    5487: {
        n: "Grace",
        d: "<span style='color:#3388ff'>Grace　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'> <br /> </span><span style='color:#ffcb4a'>Bị động <br /> </span><span style='color:#ffffff'>After casting </span><span style='color:#ffcb4a'>Shifting Constellation</span><span style='color:#ffffff'>, </span><span style='color:#ffcb4a'></span><span style='color:#ffffff'>you will be immune to any damage for </span><span style='color:#ffcb4a'>%.1f </span><span style='color:#ffffff;'>giây.</span>",
    },
    5488: {
        n: "Heavenly Glory",
        d: "<span style='color:#3388ff'>Heavenly Glory 　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'> <br /> </span><span style='color:#ffcb4a'>Bị động <br /> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Luna Gale </span><span style='color:#ffffff'>has a </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'>chance to reset the Thời gian hồi kỹ năng of </span><span style='color:#ffcb4a'>Emperor's Battlecry </span><span style='color:#ffffff'>and </span><span style='color:#ffcb4a'>Crossed Streams</span><span style='color:#ffffff;'>.</span>",
    },
    5489: {
        n: "Soulless Void",
        d: "<span style='color:#3388ff'>Soulless Void　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'> <br /> </span><span style='color:#ffcb4a'>Bị động <br /> </span><span style='color:#ffffff'>Extends the range of </span><span style='color:#ffcb4a'>Footprints of the Past </span><span style='color:#ffffff'>by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>meters.</span>",
    },
    5490: {
        n: "Heavenly Witchcraft",
        d: "<span style='color:#3388ff'>Heavenly Witchcraft 　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Gives </span><span style='color:#ffcb4a'>Moonshot </span><span style='color:#ffffff'>and </span><span style='color:#ffcb4a'>Luna Gale </span><span style='color:#ffffff'>a chance to Paralyze target for </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giâys based on caster's Paralyze Resistance.</span>",
    },
    5491: {
        n: "Heavenly Moon",
        d: "<span style='color:#3388ff'>Heavenly Moon 　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Enhanced </span><span style='color:#ffcb4a'>Impervious </span><span style='color:#ffffff;'>Damage Reduction by %d%%.</span>",
    },
    5492: {
        n: "Evil Spirit of Yin",
        d: "<span style='color:#3388ff'>Evil Spirit of Yin　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động<br /> Extends </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Moonshot </span><span style='color:#ffffff'>and </span><span style='color:#ffcb4a'>Luna Gale </span><span style='color:#ffffff'>Travel Distance by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> meters.</span>",
    },
    5493: {
        n: "Salty Pool",
        d: "<span style='color:#3388ff'>Salty Pool　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'> <br /> </span><span style='color:#ffcb4a'>Bị động <br /> </span><span style='color:#ffffff'>Increases </span><span style='color:#ffcb4a'>Dragonrest Shoal</span><span style='color:#ffffff'>'s Max Casts by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>, and reduces its <br /> Thời gian hồi kỹ năng by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5494: {
        n: "Major Exhaustion",
        d: "<span style='color:#3388ff'>Major Exhaustion　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'> <br /> </span><span style='color:#ffcb4a'>Bị động <br /> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Dragonrest Shoal</span><span style='color:#ffffff'>'s chance to reduce Control Time is increased </span><span style='color:#ffcb4a'>%d%% </span><span style='color:#ffffff'>with every consecutive cast. <br /> The chance to remove Control Effects is increased </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    5495: {
        n: "Airborne Interception",
        d: "<span style='color:#3388ff'>Airborne Interception　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'> <br /> </span><span style='color:#ffcb4a'>Bị động <br /> </span><span style='color:#ffffff'>Extends </span><span style='color:#ffcb4a'>Reflection of Light and Shadow</span><span style='color:#ffffff'>'s Evasion Range by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>yard(s).</span>",
    },
    5496: {
        n: "Dragon's Merit",
        d: "<span style='color:#3388ff'>Dragon's Merit　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'> <br /> </span><span style='color:#ffcb4a'>Bị động <br /> </span><span style='color:#ffffff'>Reduces </span><span style='color:#ffcb4a'>Celestial Majesty</span><span style='color:#ffffff'>'s Thời gian hồi kỹ năng by </span><span style='color:#ffcb4a'>%d </span><span style='color:#ffffff;'>giây.</span>",
    },
    5497: {
        n: "Glamor",
        d: "<span style='color:#3388ff'>Glamor　</span><span style='color:#ffffff'>%s/3<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it influences your other skills.</span>",
        u: "<span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a'>Bị động Effect<br /> </span><span style='color:#ffffff'>After Skill </span><span style='color:#ffcb4a'>Celestial Majesty</span><span style='color:#ffffff'> is used, your skill damage increases by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>, and you become immune to<br /> harmful effects. Duration: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.<br /> The duration on the Deep Thoughts skill is doubled.</span>",
    },
};
