var st = {
    t7: "Bảng 1",
    t8: "Bảng 2",
    t9: "Bảng 3",
    t10: "Thiếu Hiệp",
    218: {
        n: "Trọng Kích",
        d: "<span style='color:#ffffff'>Trọng Kích　</span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Toàn lực nhất kích! Người mới chơi thường dùng, hiệu quả cao.<br /> </span><span style='color:#ffffff'>Thời gian thi triển: 1 giây<br /> </span><span style='color:#11ff11'>Nhân vật dưới cấp 30 dùng có hiệu quả cộng thêm</span><span style='color:#ffffff;'></span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>Tấn công bổ sung </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> công kích. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    219: {
        n: "Cảnh Giác",
        d: "<span style='color:#ffffff'>Cảnh Giác　</span><span style='color:#ffcb4a'>%s/7<br /> </span><span style='color:#ffcb4a'>Luôn cảnh giác cao độ, tăng cố định tất cả kháng tính.<br /> </span><span style='color:#9900ff'>Bị động</span><span style='color:#ffffff;'></span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#ffffff'>Tất cả kháng tính tăng vĩnh viễn </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> điểm.</span>",
    },
    220: {
        n: "Dũng Khí",
        d: "<span style='color:#ffffff'>Dũng Khí　</span><span style='color:#ffcb4a'>%s/6<br /> Destiny comes to those who seize it!<br /> This skill increases your Attack.<br /> </span><span style='color:#11aaff'>Chúc phúc bản thân<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffffff'></span><span style='color:#11aaff'><br /> %d chân khí<br /> </span><span style='color:#ffffff'>Increases your Attack by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>30</span><span style='color:#ffffff'> minutes.<br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>2</span><span style='color:#ffffff;'> giây.</span>",
    },
    221: {
        n: "Heal Wounds",
        d: "<span style='color:#ffffff'>Heal Wounds　</span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Use water to restore the Health of a friendly target.<br /> </span><span style='color:#11aaff'>Blessing<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 2 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí　　　　　　　　　　<br /> </span><span style='color:#ffffff'>Restores </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> Health. Over the next </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys<br /> your target will be healed for an additional </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> Health.<br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. Healing effects do not stack.<br /> Range: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> yards.</span>",
    },
    243: {
        n: "Windrunner",
        d: "<span style='color:#ffffff'>Windrunner　</span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Run like the wind.<br /> Increase your movement speed.<br /> This ability does not affect your speed while mounted.<br /> </span><span style='color:#11aaff'>Self-Blessing<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffcb4a'>For %d giâys,</span><span style='color:#ffffff'> movement speed is increased by </span><span style='color:#ffcb4a'>%.1f</span><span style='color:#ffffff'> yards <br /> per giây and Evasion is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>80</span><span style='color:#ffffff;'> giây.</span>",
    },
    244: {
        n: "Furious Chop",
        d: "<span style='color:#ffffff'>Furious Chop　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>A powerful, vicious strike, this basic Vim<br /> technique is a good start for bringing enemies down.<br /> </span><span style='color:#ffffff'>Thời gian thi triển: 1 giây.<br /> </span><span style='color:#11aaff;'>Right-click to see how this skill is influenced by<br /> your Tome skills.</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This vicious attack deals </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage. For the next </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys,<br /> your Attack will also be raised by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>1</span><span style='color:#ffffff;'> giây</span>",
    },
    245: {
        n: "Frozen Irony",
        d: "<span style='color:#ffffff'>Frozen Irony　</span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Provoke a monster to attack you by ridiculing it.<br /> </span><span style='color:#11ff11'>First Degree Raging Grudge<br /> (Has a chance to deal damage 2 giâys after casting.)<br /> </span><span style='color:#11aaff'>Nguyền rủa đơn thể<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây.</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí　　　　　　　　　<br /> </span><span style='color:#ffffff'>Has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to force the target to attack the caster.<br /> Does not affect other players. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. Range: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> yards.<br /> *</span><span style='color:#11ff11'>Raging Grudge: Has a chance to deal %d damage 2 giâys after casting.</span><span style='color:#ffffff;'></span>",
    },
    246: {
        n: "Spite",
        d: "<span style='color:#ffffff'>Spite　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>Torment your opponents to lower their morale. <br /> This will temporarily decrease your target's<br /> maximum Spirit and Stun Resistance.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>Deals </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage and has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to decrease<br /> your target's Spirit for the next </span><span style='color:#ffcb4a'>4</span><span style='color:#ffffff'> giâys by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>. This attack<br /> will also lower their Stun Resistance by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>6</span><span style='color:#ffffff'> giây. <br /> Thời gian hồi kỹ năng: </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>8</span><span style='color:#ffffff;'> giây.</span>",
    },
    247: {
        n: "Lightning Flash",
        d: "<span style='color:#ffffff'>Lightning Flash 　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>Attacks a single target twice.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 2 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>Each attack deals </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage. <br /> The giây attack also deals </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> more damage. <br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>3</span><span style='color:#ffffff;'> giây.</span>",
    },
    248: {
        n: "Magma Blade",
        d: "<span style='color:#ffffff'>Magma Blade　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>Your weapon is engulfed in fire, burning whomever it touches.<br /> This weapon now also has a chance to briefly stun your target. <br /> </span><span style='color:#ff664a'>Scorch Range: +1 yard<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack deals </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage. Over </span><span style='color:#ffcb4a'>6</span><span style='color:#ffffff'></span><span style='color:#ffffff'> giâys, the target takes<br /> an additional </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> damage. This attack also inflicts a strength </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> Stun<br /> effect on the target that lasts for </span><span style='color:#ffcb4a'>%.1f</span><span style='color:#ffffff'> giây. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>9</span><span style='color:#ffffff;'> giây.</span>",
    },
    249: {
        n: "Wither Wood",
        d: "<span style='color:#ffffff'>Wither Wood　</span><span style='color:#ffcb4a'>%s/8<br /> </span><span style='color:#ffcb4a'>Derived from elemental energies.<br /> The power of wood is unsurpassed.<br /> Temporarily raises Stun Resistance.<br /> </span><span style='color:#cc33ff'>Wood Element Spell: CritNull Boost<br /> </span><span style='color:#aaffff'>*When Wither Wood reaches LV8, your CritNull<br /> will be increased when attacked by other players while<br /> a Stun Resistance buff status is active.<br /> *The CritNull boost will gradually<br /> become weaker as time goes on. <br /> This boost will not reduce while Blessed.<br /> </span><span style='color:#11aaff'>Self-Blessing<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>Stun Resistance is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> for<br /> </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>144</span><span style='color:#ffffff;'> giây.</span>",
    },
    250: {
        n: "Frenzied Strike",
        d: "<span style='color:#ffffff'>Frenzied Strike　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>Violently attack your target,<br /> with no concern for your health.<br /> </span><span style='color:#11ff11'>First Degree Profane Bash<br /> (15%% chance to lower your target's<br /> Defense by 5%% for 6 giây.)<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 2 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'></span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Costs %d Health</span><span style='color:#ffffff'><br /> This attack deals </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage.<br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>2</span><span style='color:#ffffff;'> giây.</span>",
    },
    251: {
        n: "Charm of Earth",
        d: "<span style='color:#ffffff'>Charm of Earth　</span><span style='color:#ffcb4a'>%s/8<br /> </span><span style='color:#ffcb4a'>Use the elemental power of earth to enhance your Health.<br /> Increases your Maximum Health.<br /> </span><span style='color:#cc33ff'>Earth Element Spell: Health Boost<br /> </span><span style='color:#aaffff'>*When Charm of Earth reaches LV8, your max Health<br /> will be increased when attacked by other players.<br /> You will immediately receive 20 stacks of the buff.<br /> *The max Health boost will gradually<br /> become weaker as time goes on. <br /> This boost will not reduce while Blessed.<br /> </span><span style='color:#9900ff'>Bị động</span><span style='color:#ffffff;'></span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#ffffff'>Your maximum Health is permanently increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    252: {
        n: "Glacier Edge",
        d: "<span style='color:#ffffff'>Glacier Edge　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>Ice-cold air emanates from your blade. The chilly temperatures <br /> freeze your adversaries, both slowing and harming them.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffcb4a'>Targets: %d<br /> </span><span style='color:#ffffff'>This attack deals damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of the caster's Attack<br /> Power to nearby targets in front of the caster, and slows them<br /> by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>10</span><span style='color:#ffffff'> giây. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>6</span><span style='color:#ffffff;'> giây.</span>",
    },
    253: {
        n: "Fog Curse",
        d: "<span style='color:#ffffff'>Fog Curse　</span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Obscure your appearance with fog to increase your defence.<br /> </span><span style='color:#9900ff'>Bị động</span><span style='color:#ffffff;'></span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#ffffff'>Defense is permanently increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    254: {
        n: "Steadfast Strike",
        d: "<span style='color:#ffffff'>Steadfast Strike　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>Your courageous stand in the face of sure destruction<br /> will dampen the enthusiasm of your enemies.<br /> This strike can lower your target's Attack Power.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack deals </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage and inflicts a strength </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'><br /> Weaken effect that can decrease your target's Attack Power by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>%%. <br /> Duration: </span><span style='color:#ffcb4a'>%.1f</span><span style='color:#ffffff'> giây. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>8</span><span style='color:#ffffff;'> giây.</span>",
    },
    255: {
        n: "Vampire Bite Curse",
        d: "<span style='color:#ffffff'>Vampire Bite Curse　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>Ancient leeching technique.<br /> Takes a percentage of damage as health regeneration.<br /> Not to be used without caution.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack deals </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage and restores Health to the caster<br /> equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of this extra damage. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>20</span><span style='color:#ffffff;'> giây.</span>",
    },
    256: {
        n: "Cherub's Dance",
        d: "<span style='color:#ffffff'>Cherub's Dance　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>A quick, multi-pronged assault.<br /> Attacks a single target three times.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 3 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack hits three times, dealing extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'><br /> of Attack Power plus </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> with each strike. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>5</span><span style='color:#ffffff;'> giây.</span>",
    },
    257: {
        n: "Demonic Betrayal",
        d: "<span style='color:#ffffff'>Demonic Betrayal　</span><span style='color:#ffcb4a'>%s/7<br /> </span><span style='color:#ffcb4a'>A demon once betrayed its kind, and taught the Vim how to dispel<br /> Silence effects. This skill dispels all of your target's Silence debuffs<br /> and increases their Silence resistance.<br /> </span><span style='color:#11aaff'>Chúc phúc quần thể<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#11aaff'>%d Spirit<br /> </span><span style='color:#ffffff'>Instantly removes Silence and Taunt Effects on target and<br /> makes the target immune to Taunt for the next </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. Also, for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys,<br /> increases Silence Resistance by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> and Channeling Range by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> meters.<br /> Cannot be used when Silenced or when Taunt Effect is active on the caster.<br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>120</span><span style='color:#ffffff;'> giây.</span>",
    },
    258: {
        n: "Demonfire",
        d: "<span style='color:#ffffff'>Demonfire　</span><span style='color:#ffcb4a'>%s/7<br /> </span><span style='color:#ffcb4a'>This discipline is based on well studied demonic assaults.<br /> Demons don't mind spilling a little blood, even when it's their own.<br /> Increase your offensive powers at the cost of your defences.<br /> </span><span style='color:#cc33ff'>Fire Element Spell: Offense Boost<br /> </span><span style='color:#aaffff'>*When Demonfire reaches LV7, your Attack Power<br /> will be increased when you hit another player. <br /> You will immediately receive 20 stacks of the buff.<br /> *The Attack Power boost will gradually <br /> become weaker as time goes on. <br /> This boost will not reduce while Blessed.<br /> </span><span style='color:#11aaff'>Self-Blessing<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>Your Attack Power will be increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>, but your Defense will be<br /> decreased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>. This effect lasts for </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>90</span><span style='color:#ffffff;'> giây.</span>",
    },
    259: {
        n: "Desecrate",
        d: "<span style='color:#ffffff'>Desecrate　</span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Provoke the attention of your enemies<br /> by violating the most sacred rules of war.<br /> </span><span style='color:#11ff11'>giây Degree Raging Grudge<br /> (For two giâys after being provoked,<br /> targets will take bonus damage.)<br /> </span><span style='color:#11aaff'>Nguyền rủa đa mục tiêu<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí　　　　　　　　　　<br /> </span><span style='color:#ffffff'>This act provokes targets within </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> yards of you. Each target has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'><br /> chance to be forced to attack you. This does not affect other players.<br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. Range: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> yards.<br /> *</span><span style='color:#11ff11'>Raging Grudge causes attacks to deal %d more damage.</span><span style='color:#ffffff;'>*</span>",
    },
    260: {
        n: "Sharpen Steel",
        d: "<span style='color:#ffffff'>Sharpen Steel　</span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Sharpen your blades with elemental energy. <br /> Both your own Attack Power and that of your nearby allies is temporarily increased.<br /> </span><span style='color:#cc33ff'>Metal Element Spell: Accuracy Boost<br /> </span><span style='color:#aaffff'>*When Sharpen Steel reaches Rank 5, your Accuracy<br /> will be increased when you hit another player. <br /> You will immediately receive 20 stacks of the buff.<br /> *The Accuracy boost will gradually become weaker as<br /> time goes on. This boost will not reduce while Blessed.<br /> </span><span style='color:#11aaff'>Blessing (Party, Centered on caster)<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 2 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>Both the caster and members of the caster's party within </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> yards of the caster have their<br /> Attack Power increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>. This effect lasts for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> minutes. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>2</span><span style='color:#ffffff;'> giây.</span>",
    },
    261: {
        v: 1,
        n: "Counter Tide",
        d: "<span style='color:#ffffff'>Counter Tide　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>This ability, derived from the tides themselves,<br /> uses subtlety to inflict extra damage on your opponent.<br /> Has a chance to remove target's speed-up status and slows target.<br /> </span><span style='color:#cc33ff'>Water Element Spell: Ailment Recovery<br /> </span><span style='color:#aaffff'>*When Counter Tide reaches LV9, your Recovery <br /> will be increased when attacked by other players.<br /> You will immediately receive 20 stacks of the buff.<br /> *The Recovery boost will gradually<br /> become weaker as time goes on. <br /> This boost will not reduce while Blessed.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack deals </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage, and has a chance to<br /> decrease the target's movement speed by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>%.1f</span><span style='color:#ffffff'> giây.<br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>6</span><span style='color:#ffffff'> giây. <br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'> chance to remove target's speed-up status.</span>",
    },
    262: {
        n: "Cherub's Song",
        d: "<span style='color:#ffffff'>Cherub's Song　</span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Summon the power of the heavens.<br /> Increases target's max Health.<br /> Increases target's Attack Power.<br /> </span><span style='color:#11aaff'>Blessing (Single Target, any friendly)<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 3 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d Spirit　　　　　　　　　　　<br /> </span><span style='color:#ffffff'>Increase target's max Health by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> and Attack Power by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'><br /> </span><span style='color:#ffffff'>for </span><span style='color:#ffcb4a'>30</span><span style='color:#ffffff'> minutes. Doesn't stack with </span><span style='color:#ffff11'>Sharpen Steel</span><span style='color:#ffffff'>.<br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>6</span><span style='color:#ffffff'> giây.<br /> Range: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> yards.</span>",
    },
    263: {
        n: "Divine Inspiration",
        d: "<span style='color:#ffffff'>Divine Inspiration　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>A teaching passed down through the ages <br /> from Lunar Wind Ancients to subsequent students.<br /> Attacks target's morale, lowering resistance to Weakening effects.<br /> </span><span style='color:#11ff11'>giây Degree Profane Bash<br /> 20%% chance to weaken target by 7%% for 8 giây.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack<br /> Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>, and reduces the target's Weaken<br /> Resistance by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>2</span><span style='color:#ffffff;'> giây.</span>",
    },
    264: {
        n: "Djinn Fire",
        d: "<span style='color:#ffffff'>Djinn Fire　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>From the Book of Djinns. Channel Spirit through<br /> your weapon and towards a single target.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 2 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'><br /> of its Spirit cost. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>60</span><span style='color:#ffffff;'> giây.</span>",
    },
    314: {
        n: "Infatuation",
        d: "<span style='color:#ffffff'>Infatuation　</span><span style='color:#ffcb4a'>%s/8<br /> </span><span style='color:#ffcb4a'>'Spirits, surround me! Give me the strength to save my<br /> friend's life at the cost of my own!' This technique<br /> allows a Vim disciple to sacrifice their own health in<br /> order to protect an ally from harm.<br /> </span><span style='color:#11aaff'>Blessing (Any Player Target)<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 2 giây.</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí　　　　　　　　　<br /> </span><span style='color:#ffffff'>Costs </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Max Health<br /> For </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys, damage taken by the target is reduced by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>. <br /> The amount of damage reduced will not exceed<br /> </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> points. If your Health is lower than </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>,<br /> using this skill will instantly reduce your Health to 1.<br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>2</span><span style='color:#ffffff'> minutes. Range: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> yards.</span>",
    },
    315: {
        n: "Hopeless Passion",
        d: "<span style='color:#ffffff'>Hopeless Passion　</span><span style='color:#ffcb4a'>%d/6<br /> </span><span style='color:#ffcb4a'>'We must always strive for our goals, even when they seem unattainable.'<br /> Increases your Health and Spirit.<br /> </span><span style='color:#9900ff'>Bị động</span><span style='color:#ffffff;'></span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#ffffff'>Permanently increases max HP and max SP<br /> by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> times your current level.</span>",
    },
    393: {
        n: "Charge",
        d: "<span style='color:#ffffff'>Charge　</span><span style='color:#ffcb4a'>%s/3<br /> </span><span style='color:#ffcb4a'>A burst of energy allows you to leap forward at high speed, <br /> and has a chance to free you from a debilitating Slow effect.<br /> </span><span style='color:#ffffff;'>Cannot be used while mounted.<br /> Instant Cast.</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. Your next attack will deal </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> extra damage.<br /> You must attack within </span><span style='color:#ffcb4a'>8</span><span style='color:#ffffff;'> giâys of charging to gain this benefit.</span>",
    },
    462: {
        n: "Blood Oath",
        d: "<span style='color:#ffffff'>Blood Oath　</span><span style='color:#ffcb4a'>%s/3<br /> </span><span style='color:#ffcb4a'>Trade your blood for the power of the spirits.<br /> Your Maximum Spirit is increased.<br /> </span><span style='color:#9900ff'>Bị động</span><span style='color:#ffffff;'></span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#ffffff'>Max Spirit is permanently increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    463: {
        n: "Dexterity",
        d: "<span style='color:#ffffff'>Dexterity　</span><span style='color:#ffcb4a'>%s/3<br /> </span><span style='color:#ffcb4a'>'How much can one learn from nothingness?'<br /> Increases Sleep Resistance and Skill Evasion.<br /> </span><span style='color:#9900ff'>Bị động</span><span style='color:#ffffff;'></span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#ffffff'>Permanently increases Sleep RES by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> <br /> and Skill Evasion by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    519: {
        n: "Tyrant Slayer",
        d: "<span style='color:#ffffff'>Tyrant Slayer　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>Launch an overwhelming assault.<br /> Attack a melee target with a<br /> chance to decrease Attack Power.<br /> </span><span style='color:#11ff11'>Profane Bash +3 (25%% chance to decrease<br /> target's Defense by 9%% for 10 giây.)<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 2 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack deals </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage and has<br /> a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to decrease the target's Attack<br /> Power by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>8</span><span style='color:#ffffff'> giây. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>4</span><span style='color:#ffffff'> giây.<br /> *</span><span style='color:#11ff11'>Profane Bash Curse: Deals an additional %d<br /> damage 2 giâys after Profane Bash bonus effect<br /> is successfully applied.</span><span style='color:#ffffff;'></span>",
    },
    520: {
        n: "Splitting Strike",
        d: "<span style='color:#ffffff'>Splitting Strike　</span><span style='color:#ffcb4a'>%s/3<br /> </span><span style='color:#ffcb4a'>Knock your enemy into an abyss.<br /> Makes a ranged attack on an enemy.<br /> Has a chance to slow the target.<br /> This slow effect cannot be removed.<br /> </span><span style='color:#11ff11'>giây Degree Raging Grudge<br /> (Deals additional damage 2 giâys after a successful cast.)<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack deals damage at </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power to a target within<br /> </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'></span><span style='color:#ffffff'> yards, and has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to reduce the target's movement speed by<br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. This effect is more likely to succeed if the target's<br /> Health is low. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>60</span><span style='color:#ffffff'> giây.<br /> If </span><span style='color:#11ff11'>Splitting Strike</span><span style='color:#ffffff'> lands a CritStrike, the target's movement speed buffs are removed.<br /> *</span><span style='color:#11ff11'>Raging Grudge: Deals %d additional damage 2 giâys after casting.</span><span style='color:#ffffff;'>*</span>",
    },
    521: {
        n: "Gather Spirit",
        d: "<span style='color:#ffffff'>Gather Spirit　</span><span style='color:#ffcb4a'>%s/7<br /> </span><span style='color:#ffcb4a'>IOne of the six occult skills <br />  improved to make more powerful by the Cult Elders.<br /> Uses half your Spirit to attack the<br /> single target close to you.<br /> </span><span style='color:#ff2222'>Bloodbath Blade-Serial Slash: If you use this skill to kill<br /> the target, the Thời gian hồi kỹ năng of this skill won't reset. Every </span><span style='color:#11ff11'>1</span><span style='color:#ffffff'></span><span style='color:#ff2222'> minutes,<br /> this skill can be used </span><span style='color:#11ff11'>2</span><span style='color:#ff2222'> times.<br /> </span><span style='color:#ffffff;'>1 giây cast</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>Costs Half Spirit<br /> </span><span style='color:#ffffff'>The caster's Attack Power has no effect on the damage dealt.<br /> </span><span style='color:#ffffff'>This attack deals damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of the caster's Max Spirit. <br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>75</span><span style='color:#ffffff;'> giây.</span>",
    },
    522: {
        n: "Nascent Raja",
        d: "<span style='color:#ffffff'>Nascent Raja　</span><span style='color:#ffcb4a'>%s/8<br /> </span><span style='color:#ffcb4a'>A cult's most powerful spell for evil.<br /> Provides invulnerability to attacks and immunity<br /> against negative effects for a brief period of time.<br /> </span><span style='color:#11ff11'><br /> (For 2 giâys after casting, the caster is invulnerable.)<br /> </span><span style='color:#11aaff'>Self-Blessing<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffcb4a'>For %d giâys,</span><span style='color:#ffffff'> the caster is invulnerable to the next </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'><br /> attacks or negative effects. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>120</span><span style='color:#ffffff;'> giây.</span>",
    },
    523: {
        n: "Dragonfury",
        d: "<span style='color:#ffffff'>Dragonfury　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>Emulate the fury of a dragon and absorb the<br /> vigor of all beings. Attack a target twice with<br /> a chance to decrease its max Health and Spirit.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 2 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack hits twice, dealing </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage with each strike.<br /> Has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to decrease the target's max Health by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> and<br /> their max Spirit by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>9</span><span style='color:#ffffff;'> giây.</span>",
    },
    524: {
        n: "Demon Blood",
        d: "<span style='color:#ffffff'>Demon Blood　</span><span style='color:#ffcb4a'>%s/8<br /> </span><span style='color:#ffcb4a'>One of the six forbidden spells from the underworld.<br /> Encourages the growth of strength.<br /> For a brief period, Defense is increased when attacked.<br /> </span><span style='color:#11aaff'>Self-Blessing<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí</span><span style='color:#ffcb4a'><br /> For the next %d giâys defence is increased by </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>%d each time you are hit. <br /> </span><span style='color:#ffffff'>This can stack up to </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> times. Removes </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> debuffs currently active upon yourself.<br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>120</span><span style='color:#ffffff;'> giâys</span>",
    },
    525: {
        n: "Mad Spiral",
        d: "<span style='color:#ffffff'>Mad Spiral　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>Trapped in the Abyss with no salvation!<br /> Swiftly attack your target four times.<br /> </span><span style='color:#11ff11'>Vim</span><span style='color:#ffffff'> </span><span style='color:#11ff11'>Essence of Spells<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 4 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>This attack hits four times, dealing extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'><br /> of Attack Power plus </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> with each strike. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>10</span><span style='color:#ffffff'> giây.<br /> *</span><span style='color:#11ff11'></span><span style='color:#ffcb4a'>%d%% chance: Target is disarmed for </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>%d giây.</span><span style='color:#ffffff'><br /> *</span><span style='color:#11ff11'></span><span style='color:#ffcb4a'>%d%% chance: Over </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>%d giâys, restores </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>%d%% of caster's Health.</span><span style='color:#ffffff;'></span>",
    },
    526: {
        n: "Perpetual Loneliness",
        d: "<span style='color:#ffffff'>Perpetual Loneliness　</span><span style='color:#ffcb4a'>%s/7<br /> </span><span style='color:#ffcb4a'>Freeze the world in darkness...<br /> Paralyzes all surrounding targets. <br /> Ignores Paralyze Resistance.<br /> </span><span style='color:#11aaff'>Nguyền rủa đa mục tiêu<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d Spirit<br /> </span><span style='color:#ffcb4a'>Targets: %d <br /> </span><span style='color:#ffffff'>Paralyzes and slows all targets within </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> yards for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. <br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>120</span><span style='color:#ffffff;'> giây.</span>",
    },
    527: {
        n: "Sangjo Array",
        d: "<span style='color:#ffffff'>Sangjo Array　</span><span style='color:#ffcb4a'>%s/9<br /> </span><span style='color:#ffcb4a'>The end is near and the gods have turned their backs.<br /> Summon a magical array to damage surrounding targets.<br /> </span><span style='color:#ffffff'>Instant Cast<br /> </span><span style='color:#ffffff'></span><span style='color:#ffcb4a'>Caster's</span><span style='color:#ffffff'> </span><span style='color:#ffcb4a'>PvP Settings</span><span style='color:#ffffff'> determine which targets are valid.<br /> Cannot be cancelled while casting.<br /> </span><span style='color:#ff1111'>Be aware of your PVP settings. Use in PVP mode can increase Infamy.<br /> </span><span style='color:#11ff11'>Chúc phúc quần thể</span><span style='color:#ffffff;'></span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#ffffff'>Every </span><span style='color:#ffcb4a'>5</span><span style='color:#ffffff'> giâys, strike targets within </span><span style='color:#ffcb4a'>%.1f</span><span style='color:#ffffff'> yards. <br /> Deals damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power. <br /> Reduces the CritNull by </span><span style='color:#ffcb4a'>%.1f%%</span><span style='color:#ffffff'> of up to </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> targets. <br /> Duration: </span><span style='color:#ffcb4a'>1</span><span style='color:#ffffff'> hour. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>12</span><span style='color:#ffffff'> giây. <br /> The array will increase your Accuracy by </span><span style='color:#ffcb4a'>%.1f</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>60</span><span style='color:#ffffff'> giây. <br /> </span><span style='color:#11aaff'>*</span><span style='color:#11ff11'> Caster can move after casting this array. <br /> </span><span style='color:#11aaff'>*</span><span style='color:#11ff11'> Every </span><span style='color:#ffcb4a'>5</span><span style='color:#11ff11'> giâys, </span><span style='color:#ffcb4a'>%d</span><span style='color:#11ff11'> Spirit is used to maintain array. <br /> </span><span style='color:#11aaff'>*</span><span style='color:#11ff11'> Cast again to deactivate the array. <br /> </span><span style='color:#11aaff'>*</span><span style='color:#11ff11'> Insufficient Spirit will automatically cancel the array.</span><span style='color:#ffffff;'></span>",
    },
    775: {
        n: "Mohun Juma",
        d: "<span style='color:#ffffff'>Mohun Juma　</span><span style='color:#ffcb4a'>%s/6<br /> </span><span style='color:#ffcb4a'>Exclusive skill of the Vim Elders. It was created by Meri Koon<br /> and improved by Master Vim. Famous for its swiftness,<br /> attacks a group four times dealing a random amount of damage.<br /> </span><span style='color:#11ff11'>One Lethal Strike+4<br /> (30%% chance to reduce target's defence by 11%% for 12 giâys)<br /> </span><span style='color:#ffffff;'>2 giây cast</span>",
        u: "<span style='color:#ffcb4a'><br /> </span><span style='color:#11aaff'>%d Spirit<br /> </span><span style='color:#ffcb4a'>Targets Amount Limit: %d<br /> </span><span style='color:#ffffff'>Increases Attack Power by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> plus<br /> </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> Attack Power. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>9</span><span style='color:#ffffff'> giây.<br /> </span><span style='color:#11ff11'>One Lethal Strike: Curse+2<br /> (If One Lethal Strike works, in 2 giâys %d settled damage<br /> will be added.)</span><span style='color:#ffffff;'></span>",
    },
    776: {
        n: "Clever Rebuttal",
        d: "<span style='color:#ffffff'>Clever Rebuttal　</span><span style='color:#ffcb4a'>%s/5<br /> </span><span style='color:#ffcb4a'>Wall paintings were discovered in a cave on Foxhill. Their origin is unknown but <br /> they seem to be in accord with Vim teachings. <br /> While effect lasts, damage is reflected and caster becomes immune to sleep.<br /> </span><span style='color:#11aaff'>Self-Blessing<br /> </span><span style='color:#ffffff'>When activated, checks </span><span style='color:#ffcb4a'></span><span style='color:#ffffff'>caster's </span><span style='color:#ffcb4a'>PvP Settings</span><span style='color:#ffffff'> to determine<br /> whether or not damage can be reflected.<br /> While effect lasts, PvP settings cannot be changed.<br /> </span><span style='color:#ff1111'>Use with caution. If opponent dies from reflected damage, infamy will increase.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 1 giây</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>For </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys, </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of damage taken by the caster is reflected<br /> back at the attacker. For the first </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys of this effect, the<br /> caster is immune to Sleep effects. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>180</span><span style='color:#ffffff;'> giây.</span>",
    },
    777: {
        n: "Dawn's End",
        d: "<span style='color:#ffffff'>Dawn's End　</span><span style='color:#ffcb4a'>%s/4<br /> </span><span style='color:#ffcb4a'>A supreme skill only recently<br /> adopted into standard Vim teachings.<br /> Attack surrounding targets with a<br /> chance to taunt enemies.<br /> </span><span style='color:#11ff11'>Third Degree Raging Grudge<br /> (Additional damage is dealt 2 giâys after taunt succeeds.)<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 2 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffcb4a'>Targets: %d <br /> </span><span style='color:#ffffff'>This attack hits targets within </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> yards of the caster, dealing </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra<br /> damage to each target, with a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to force the targets to attack<br /> the caster. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>20</span><span style='color:#ffffff'> giây.<br /> *</span><span style='color:#11ff11'>Raging Grudge: Deals %d damage 2 giâys after successful taunt.</span><span style='color:#ffffff;'></span>",
    },
    778: {
        n: "Nameless Technique",
        d: "<span style='color:#ffffff'>Nameless Technique　</span><span style='color:#ffcb4a'>%s/2<br /> </span><span style='color:#ffcb4a'>This deadly spell, summoned from the<br /> spirits of blood, is now the ultimate Vim skill.<br /> Attacks a melee target six times.<br /> </span><span style='color:#11ff11'>Vim's</span><span style='color:#ffffff'> </span><span style='color:#11ff11'>Final Chance.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 3 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffffff'>Increases damage by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power.<br /> Each strike adds </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage. Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>15</span><span style='color:#ffffff'> giây.<br /> </span><span style='color:#11ff11'></span><span style='color:#ffcb4a'>For %d</span><span style='color:#ffffff'> giâys, the caster has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to<br /> reduce all incoming damage by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> </span><span style='color:#11ff11'></span><span style='color:#ffffff'>and also has a chance<br /> to weaken the target by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. Weaken Effect: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'><br /> </span><span style='color:#11ff11'></span><span style='color:#ffcb4a'>For %d</span><span style='color:#ffffff'> giâys, the caster has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance<br /> to decrease the target's Spirit by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of the target's max Health.<br /> </span><span style='color:#11ff11'>*</span><span style='color:#ffffff'>Increases Attack by </span><span style='color:#ffcb4a'>%d%%.</span><span style='color:#ffffff'><br /> </span><span style='color:#ffcb4a;'>　<br /> </span>",
        p1: "<span style='color:#cc33ff'>Firmus·Arcane Charge<br /> </span><span style='color:#11ff11'>*</span><span style='color:#ffcb4a'>The skill's power will increase as the Esper upgrades.</span><span style='color:#11ff11'>*<br /> </span><span style='color:#11ff11'>When the Esper reaches LV5, damage increases by </span><span style='color:#ffcb4a'>20%</span><span style='color:#11ff11'> of Attack Power.<br /> Grants </span><span style='color:#ffcb4a'>15%</span><span style='color:#11ff11'> Damage Reduction, and increases attack range by 3 meters.</span><span style='color:#11ff11;'></span>",
    },
    618: {
        n: "Infuse Kang Mo",
        d: "<span style='color:#3388ff'>Infuse Kang Mo　</span><span style='color:#ffffff'>%s/2<br /> </span><span style='color:#11aaff;'>Right-click a Tome skill to see how it affects your other skills.</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Furious Chop</span><span style='color:#ffffff'>'s damage is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>, <br /> plus an additional </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> per rank.</span>",
    },
    619: {
        n: "Swiftness",
        d: "<span style='color:#3388ff'>Swiftness　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Windrunner</span><span style='color:#ffffff'>'s Evasion bonus is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>, the<br /> duration of the Evasion effect is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây(s) <br /> per Rank, and the Thời gian hồi kỹ năng is reduced by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. <br /> </span><span style='color:#11ff11'>While mounted</span><span style='color:#ffffff'>, for </span><span style='color:#ffcb4a'>12</span><span style='color:#ffffff'> giâys, movement speed is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> yards per giây. <br /> When </span><span style='color:#11ff11'>Swiftness</span><span style='color:#ffffff'> reaches Rank 2, player is immune to the Slow effect for </span><span style='color:#ffcb4a'>8</span><span style='color:#ffffff'> and movement speed is <br /> increased by an additional </span><span style='color:#ffcb4a'>%.1f</span><span style='color:#ffffff'> yards per giây, and it grants additional </span><span style='color:#11ff11'>Mount Swiftness</span><span style='color:#ffffff'>. <br /> The duration of this effect, in giâys, is equal to </span><span style='color:#11ff11'>Windrunner</span><span style='color:#ffffff'></span><span style='color:#11ff11'></span><span style='color:#ffffff'>'s rank multiplied by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    620: {
        n: "Incandescence",
        d: "<span style='color:#3388ff'>Incandescence　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Magma Blade</span><span style='color:#ffffff'>'s bleed damage is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'><br /> and its Thời gian hồi kỹ năng is reduced by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây(s).<br /> When </span><span style='color:#11ff11'>Djinn Fire</span><span style='color:#ffffff'> reaches Rank </span><span style='color:#ffcb4a'>9</span><span style='color:#ffffff'>, <br /> it reduces the target's CritNull for </span><span style='color:#ffcb4a'>16</span><span style='color:#ffffff'> giâys by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    621: {
        n: "Fire Dance",
        d: "<span style='color:#3388ff'>Fire Dance　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Magma Blade</span><span style='color:#ffffff'>'s Stun strength is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> per rank,<br /> and the Stun effect's duration is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> </span><span style='color:#11ff11'>Vampire Bite Curse</span><span style='color:#ffffff'> restores </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> more Health per rank.</span>",
    },
    622: {
        n: "Bingsi Chill",
        d: "<span style='color:#3388ff'>Bingsi Chill　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Glacier Edge</span><span style='color:#ffffff'> deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of the<br /> target's level if its Slow effect is successfully applied.<br /> </span><span style='color:#11ff11'>Counter Tide</span><span style='color:#ffffff'> deals extra damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'> of the<br /> target's level if its Slow effect is successfully applied.</span>",
    },
    623: {
        n: "Fire Proficiency",
        d: "<span style='color:#3388ff'>Fire Proficiency　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Demonfire</span><span style='color:#ffffff'> grants an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> Attack Power, and<br /> has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'> chance to not reduce the caster's Defense.</span>",
    },
    624: {
        n: "Criminal Intent",
        d: "<span style='color:#3388ff'>Criminal Intent　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Steadfast Strike</span><span style='color:#ffffff'>'s damage is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> per rank, and<br /> Weakened targets' Attack Power is reduced by an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> </span><span style='color:#11ff11'>Nameless Technique</span><span style='color:#ffffff'>'s Weaken strength is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>, and<br /> Weakened targets' Attack Power is reduced by an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    625: {
        n: "Fright",
        d: "<span style='color:#3388ff'>Fright　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Steadfast Strike</span><span style='color:#ffffff'>'s Weaken strength is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> per rank,<br /> its Weaken effect's duration is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys,<br /> and its Thời gian hồi kỹ năng is reduced by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây(s).</span>",
    },
    626: {
        n: "Soul Corruption",
        d: "<span style='color:#3388ff'>Soul Corruption　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Spite</span><span style='color:#ffffff'> lowers the target's Stun Resistance by an additional </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> per rank,<br /> and the Resistance reduction effect's duration is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây.<br /> Has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to Stun the target for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây(s), ignoring Resistances.</span>",
    },
    627: {
        n: "Vampire Bite",
        d: "<span style='color:#3388ff'>Vampire Bite　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Vampire Bite Curse</span><span style='color:#ffffff'>'s Health restoration effect is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> <br /> and its Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    628: {
        n: "Jetokin Nightmare",
        d: "<span style='color:#3388ff'>Jetokin Nightmare　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Vampire Bite Curse</span><span style='color:#ffffff'>'s CritStrike Rate is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>, and it has a <br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to lower the target's Max Health by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>%% for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. <br /> </span><span style='color:#11ff11'>Dawn's End</span><span style='color:#ffffff'>'s CritStrike Rate is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>, <br /> and its chance to taunt the targets is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    629: {
        n: "Isolation",
        d: "<span style='color:#3388ff'>Isolation　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Djinn Fire</span><span style='color:#ffffff'> has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to Stun the <br /> target for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys, ignoring Resistances.<br /> </span><span style='color:#11ff11'>Nameless Technique</span><span style='color:#ffffff'>'s first strike deals additional damage equal to <br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power, and its Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    630: {
        n: "Fel Edge",
        d: "<span style='color:#3388ff'>Fel Edge　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>The flat damage bonus of all one-hit, single-target skills is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> </span><span style='color:#ffffff'>Affected skills: </span><span style='color:#11ff11'>Furious Chop</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Magma Blade</span><span style='color:#ffffff'>, <br /> </span><span style='color:#11ff11'>Steadfast Strike</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Spite</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Frenzied Strike</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Divine Inspiration</span><span style='color:#ffffff'>, <br /> </span><span style='color:#11ff11'>Vampire Bite Curse</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Djinn Fire</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Tyrant Slayer</span><span style='color:#ffffff;'>.</span>",
    },
    631: {
        n: "Pompous Speech",
        d: "<span style='color:#3388ff'>Pompous Speech　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Dragonfury</span><span style='color:#ffffff'>'s Max Health and Spirit reduction is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> The chance for this effect to succeed is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    632: {
        n: "Faith",
        d: "<span style='color:#3388ff'>Faith　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Wither Wood</span><span style='color:#ffffff'> increases Stun Resistance by an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>, <br /> with a chance to increase Stun Resistance by an even greater amount. <br /> </span><span style='color:#11ff11'>Nascent Raja</span><span style='color:#ffffff'> can nullify damage </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> more times per rank. <br /> When </span><span style='color:#11ff11'>Faith</span><span style='color:#ffffff'> reaches rank </span><span style='color:#ffcb4a'>2</span><span style='color:#ffffff'>, player can become invulnerable for </span><span style='color:#ffcb4a'>2</span><span style='color:#ffffff'> giây. <br /> </span><span style='color:#11ff11'>Nascent Raja II</span><span style='color:#ffffff'>'s Defense bonus is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    633: {
        n: "End of Days",
        d: "<span style='color:#3388ff'>End of Days　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Perpetual Loneliness</span><span style='color:#ffffff'>'s Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> </span><span style='color:#11ff11'>Dawn's End</span><span style='color:#ffffff'> deals additional damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> <br /> of Attack Power, and its Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    634: {
        n: "Misstep",
        d: "<span style='color:#3388ff'>Misstep　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Single-target offensive skills deal additional damage equal <br /> to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power and have a chance, based on <br /> the skill's rank, to decrease the target's Max Health by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> </span><span style='color:#ffffff'>Affected skills: </span><span style='color:#11ff11'>Magma Blade</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Counter Tide</span><span style='color:#ffffff'>, <br /> </span><span style='color:#11ff11'>Steadfast Strike</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Spite</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Djinn Fire</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Dragonfury</span><span style='color:#ffffff;'>.</span>",
    },
    635: {
        n: "Blood Smear",
        d: "<span style='color:#3388ff'>Blood Smear　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Blood Oath</span><span style='color:#ffffff'> increases Max Spirit by an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'> per rank.</span>",
    },
    636: {
        n: "Unmatched Valor",
        d: "<span style='color:#3388ff'>Unmatched Valor　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Courage</span><span style='color:#ffffff'> increases Attack Power by an additional </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> per rank. <br /> CritNull is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    637: {
        n: "Spirit of War",
        d: "<span style='color:#3388ff'>Spirit of War　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Sharpen Steel</span><span style='color:#ffffff'>'s Attack Power bonus is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'><br /> and its duration is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> minutes.</span>",
    },
    638: {
        n: "Icy Edge",
        d: "<span style='color:#3388ff'>Icy Edge　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Glacier Edge</span><span style='color:#ffffff'> and </span><span style='color:#11ff11'>Counter Tide</span><span style='color:#ffffff'>'s speed reduction is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>,<br /> and the duration of this effect is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    639: {
        n: "Deceit",
        d: "<span style='color:#3388ff'>Deceit　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Frozen Irony</span><span style='color:#ffffff'>'s Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys,<br /> and casting it grants you immunity to Silence for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    640: {
        n: "Celestial Rain",
        d: "<span style='color:#3388ff'>Celestial Rain　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Profane Bash</span><span style='color:#ffffff'>'s chance to take effect is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> <br /> and its duration is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây.<br /> </span><span style='color:#ffffff'>Affected skills: </span><span style='color:#11ff11'>Frenzied Strike</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Divine Inspiration</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Tyrant Slayer</span><span style='color:#ffffff'>, <br /> </span><span style='color:#11ff11'>Mohun Juma</span><span style='color:#ffffff;'>.</span>",
    },
    641: {
        n: "Fog",
        d: "<span style='color:#3388ff'>Fog　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Fog Curse</span><span style='color:#ffffff'> increases Stun Resistance by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> per rank.</span>",
    },
    642: {
        n: "Demonheart",
        d: "<span style='color:#3388ff'>Demonheart　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động (Faction Skill)<br /> </span><span style='color:#11ff11'>Wither Wood</span><span style='color:#ffffff'> increases Stun Resistance by an additional </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> points per rank.<br /> </span><span style='color:#11ff11'>Demonic Betrayal</span><span style='color:#ffffff'> increases Silence Resistance by an additional </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> points per rank.<br /> </span><span style='color:#11ff11'>Demon Blood</span><span style='color:#ffffff'> increases Defense by an additional </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> points per rank.<br /> </span><span style='color:#ffcb4a'>Bị động (Affinity Skill)<br /> </span><span style='color:#11ff11'>Demon Blood II</span><span style='color:#ffffff'> increases Defense by an additional </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> points per rank.</span>",
    },
    643: {
        n: "Heaven's Shadow",
        d: "<span style='color:#3388ff'>Heaven's Shadow　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Desecrate</span><span style='color:#ffffff'>'s Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys, <br /> and it reduces the target's Stun Resistance by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    644: {
        n: "Divine Wrath",
        d: "<span style='color:#3388ff'>Divine Wrath　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Profane Bash</span><span style='color:#ffffff'> reduces Defense by an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> and has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> <br /> chance to reduce the target's Defense by an even greater amount.<br /> </span><span style='color:#ffffff'>Affected skills: </span><span style='color:#11ff11'>Frenzied Strike</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Divine Inspiration</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Tyrant Slayer</span><span style='color:#ffffff'>, and<br /> </span><span style='color:#11ff11'>Mohun Juma</span><span style='color:#ffffff;'>.</span>",
    },
    645: {
        n: "Unrelenting Resentment",
        d: "<span style='color:#3388ff'>Unrelenting Resentment　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Raging Grudge</span><span style='color:#ffffff'> deals </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> more damage, <br /> with a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to deal even more damage. <br /> </span><span style='color:#ffffff'>Affected skills: </span><span style='color:#11ff11'>Frozen Irony</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Desecrate</span><span style='color:#ffffff'>, <br /> </span><span style='color:#11ff11'>Splitting Strike</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Dawn's End</span><span style='color:#ffffff'>. <br /> </span><span style='color:#11ff11'>Splitting Strike</span><span style='color:#ffffff'>'s Crit Strike Rate is increased, within </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    646: {
        n: "Unbridled Madness",
        d: "<span style='color:#3388ff'>Unbridled Madness　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Cherub's Song</span><span style='color:#ffffff'> increases Max Health by an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'><br /> and Attack Power by an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    647: {
        n: "Absurd Notion",
        d: "<span style='color:#3388ff'>Absurd Notion　</span><span style='color:#ffffff;'>%s/4</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>All </span><span style='color:#11ff11'>Vim Enhancement</span><span style='color:#ffffff'> skill durations are increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây. <br /> Each skill also increases your max Health by an amount equal to <br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of your max Spirit and your CritShield by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> This effect lasts for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> minute(s) and cannot be removed.<br /> </span><span style='color:#ffffff'>Affected skills: </span><span style='color:#11ff11'>Wither Wood</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Demonic Betrayal</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Demonfire</span><span style='color:#ffffff'>, <br /> </span><span style='color:#11ff11'>Infatuation</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Demon Blood</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Clever Rebuttal</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Demon Blood II</span><span style='color:#ffffff'>,<br /> </span><span style='color:#11ff11'>Clever Rebuttal <Arcane></span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Clever Rebuttal <Bane></span><span style='color:#ffffff'>, </span>^and <span style='color:#11ff11'>Clever Rebuttal <Zen></span><span style='color:#ffffff'>.<br /> When </span><span style='color:#11ff11'>Absurd Notion</span><span style='color:#ffffff'> reaches LV</span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>, and your current Health is higher than<br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of your max Health, using </span><span style='color:#11ff11'>any one</span><span style='color:#ffffff;'> of the skills above will<br /> immediately recover all of your Health.</span></span>",
    },
    648: {
        n: "Focused Hate",
        d: "<span style='color:#3388ff'>Focused Hate　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Perpetual Loneliness</span><span style='color:#ffffff'>'s duration is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>,<br /> and it also Silences the target for <br /> </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây(s).</span>",
    },
    649: {
        n: "Heaven's Blessing",
        d: "<span style='color:#3388ff'>Heaven's Blessing　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Nascent Raja</span><span style='color:#ffffff'>'s duration is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys<br /> and its Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây.<br /> </span><span style='color:#11ff11'>Nascent Raja II</span><span style='color:#ffffff'>'s Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    650: {
        n: "Sacred Word",
        d: "<span style='color:#3388ff'>Sacred Word　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Infatuation</span><span style='color:#ffffff'>'s maximum damage reduction amount is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>. <br /> Each rank in this skill will increase Defense by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>.<br /> </span><span style='color:#11ff11'>Infatuation II</span><span style='color:#ffffff'>'s maximum damage reduction amount is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> </span><span style='color:#11ff11'>Gather Spirit</span><span style='color:#ffffff'> deals additional damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power.<br /> </span><span style='color:#11ff11'>Nameless Technique</span><span style='color:#ffffff'>'s chance of reducing damage taken is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    651: {
        n: "Solitude",
        d: "<span style='color:#3388ff'>Solitude　</span><span style='color:#ffffff'>%s/4<br /> </span><span style='color:#ffcb4a'>There's a downside to being stronger than anyone else:<br /> everyone who could have challenged you is dead.<br /> </span><span style='color:#ffffff;'>Thời gian thi triển: 2 giâys</span>",
        u: "<span style='color:#ffcb4a'>　<br /> </span><span style='color:#11aaff'>%d chân khí<br /> </span><span style='color:#ffcb4a'>Targets: %d <br /> </span><span style='color:#ffffff'>Attacks all targets within </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> yards, dealing </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> extra damage. <br /> For </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys, Attack Power is increased by an amount equal to your level times </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'>. <br /> Thời gian hồi kỹ năng: </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    652: {
        n: "Expel",
        d: "<span style='color:#3388ff'>Expel　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Vim Esper</span><span style='color:#ffffff'> Skill damage is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'></span><span style='color:#ffcb4a'></span><span style='color:#ffffff;'><br /> of the owner's Attack Power, and the <br /> Defense reduction effect is enhanced slightly.</span>",
    },
    653: {
        n: "Virtue's Embrace",
        d: "<span style='color:#3388ff'>Virtue's Embrace　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Charm of Earth</span><span style='color:#ffffff'> increases Health regeneration while out of combat <br /> by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> per rank, and its Max Health bonus is increased <br /> by an amount equal to your level times </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'>.</span>",
    },
    654: {
        n: "Heaven's Wings",
        d: "<span style='color:#3388ff'>Heaven's Wings　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Charge</span><span style='color:#ffffff'> increases the damage of your next attack by an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>. <br /> The duration of this effect is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    655: {
        n: "Thunderburst",
        d: "<span style='color:#3388ff'>Thunderburst　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Lightning Flash</span><span style='color:#ffffff'> has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance <br /> to drain </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of the target's Spirit <br /> </span><span style='color:#11ff11'></span><span style='color:#ffffff'>and a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to Disarm <br /> the target for </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    656: {
        n: "Desolate",
        d: "<span style='color:#3388ff'>Desolate　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Counter Tide</span><span style='color:#ffffff'>'s CritStrike Rate is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>, <br /> and it deals </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> more damage per rank.</span>",
    },
    657: {
        n: "Chains of Fate",
        d: "<span style='color:#3388ff'>Destiny's Kiss　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>For each rank in </span><span style='color:#ffcb4a'>Bị động Faction skills</span><span style='color:#ffffff'>,<br /> CritStrike Bonus is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> </span><span style='color:#ffffff'>Affected skills: </span><span style='color:#11ff11'>Charm of Earth</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Fog Curse</span><span style='color:#ffffff'>, <br /> </span><span style='color:#11ff11'>Hopeless Passion</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Blood Oath</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Dexterity</span><span style='color:#ffffff;'>.</span>",
    },
    658: {
        n: "Iron Will",
        d: "<span style='color:#3388ff'>Iron Will　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Hopeless Passion</span><span style='color:#ffffff'>'s Max Health and Spirit bonuses are increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    659: {
        n: "Exorcise",
        d: "<span style='color:#3388ff'>Exorcise　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Divine Inspiration</span><span style='color:#ffffff'> reduces the target's Weaken Resistance by an additional <br /> </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> points per rank, and the duration is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây.<br /> </span><span style='color:#11ff11'>Gather Spirit</span><span style='color:#ffffff'>'s Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    660: {
        n: "Bout of Rage",
        d: "<span style='color:#3388ff'>Bout of Rage　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Frenzied Strike</span><span style='color:#ffffff'> deals additional damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power.<br /> </span><span style='color:#11ff11'>Infatuation</span><span style='color:#ffffff'>'s Health cost is decreased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'> per rank.</span>",
    },
    661: {
        n: "Thunderfury",
        d: "<span style='color:#3388ff'>Thunderfury　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>The flat damage bonus of all multi-strike skills is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>, <br /> and their Thời gian hồi kỹ năngs are decreased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> </span><span style='color:#ffffff'>Affected skills: </span><span style='color:#11ff11'>Lightning Flash</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Cherub's Dance</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Dragonfury</span><span style='color:#ffffff'>, <br /> </span><span style='color:#11ff11'>Mad Spiral</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Mohun Juma</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Nameless Technique</span><span style='color:#ffffff;'>.</span>",
    },
    662: {
        n: "Sanguine Spirit",
        d: "<span style='color:#3388ff'>Sanguine Spirit　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'></span><span style='color:#11ff11'></span><span style='color:#ffffff'>Thời gian hồi kỹ năngs of the following skills are decreased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>:<br /> </span><span style='color:#ffffff'></span><span style='color:#11ff11'>Demonic Betrayal</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Demonfire</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Wither Wood</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Infatuation</span><span style='color:#ffffff'>,<br /> </span><span style='color:#11ff11'>Demon Blood</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Clever Rebuttal</span><span style='color:#ffffff'>, </span><span style='color:#11ff11'>Demon Blood II</span><span style='color:#ffffff'> and </span><span style='color:#11ff11'>Infatuation II</span><span style='color:#ffffff;'>.</span>",
    },
    663: {
        n: "Thundering Sky",
        d: "<span style='color:#3388ff'>Thundering Sky　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Cherub's Dance</span><span style='color:#ffffff'> deals additional damage per strike equal to<br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>/</span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>/</span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power, and its Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> </span><span style='color:#11ff11'>Mohun Juma</span><span style='color:#ffffff'> deals additional damage per strike equal to<br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>/</span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>/</span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>/</span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power, and its Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    664: {
        n: "Demonic Spirit",
        d: "<span style='color:#3388ff'>Demonic Spirit　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Tyrant Slayer</span><span style='color:#ffffff'> deals additional damage equal to </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power<br /> and decreases the target's Attack Power by an additional </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    665: {
        n: "Dragonspite",
        d: "<span style='color:#3388ff'>Dragonspite　</span><span style='color:#ffffff;'>%s/2</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Glacier Edge</span><span style='color:#ffffff'>'s Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây(s).<br /> </span><span style='color:#11ff11'>Dragonfury</span><span style='color:#ffffff'>'s Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây(s), and the <br /> duration of its Health and Spirit reduction effect is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giây.<br /> </span><span style='color:#11ff11'>Mad Spiral</span><span style='color:#ffffff'> has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> higher chance to Disarm the target, <br /> and the duration of this effect is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> giây.</span>",
    },
    666: {
        n: "Fel Endowment",
        d: "<span style='color:#3388ff'>Fel Endowment　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động (Faction Skill)<br /> </span><span style='color:#11ff11'>Demonic Betrayal</span><span style='color:#ffffff'> has a </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> chance to dispel Paralyze effects.<br /> </span><span style='color:#11ff11'>Cherub's Song</span><span style='color:#ffffff'>'s duration is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> minutes.<br /> </span><span style='color:#11ff11'>Demon Blood</span><span style='color:#ffffff'> can stack </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> more times.<br /> </span><span style='color:#11ff11'>Clever Rebuttal</span><span style='color:#ffffff'>'s Sleep immunity duration is increased by </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys, <br /> and it also grants immunity to Stun for the same duration.<br /> </span><span style='color:#ffcb4a'>Bị động (Affinity Skill)<br /> </span><span style='color:#11ff11'>Demon Blood II</span><span style='color:#ffffff'> can stack </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff;'> more times.</span>",
    },
    667: {
        n: "Nihility",
        d: "<span style='color:#3388ff'>Nihility　</span><span style='color:#ffffff;'>%s/3</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#11ff11'>Splitting Strike</span><span style='color:#ffffff'>'s effective Attack Power is increased by <br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> per rank, and its Thời gian hồi kỹ năng is decreased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
    668: {
        n: "Fel Path",
        d: "<span style='color:#3388ff'>Fel Path　</span><span style='color:#ffffff;'>%s/4</span>",
        u: "<span style='color:#ffffff'>　<br /> </span><span style='color:#ffcb4a'>Bị động<br /> </span><span style='color:#ffffff'>Increases CritShield by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>. <br /> </span><span style='color:#11ff11'>Glacier Edge</span><span style='color:#ffffff'> deals additional damage equal to <br /> </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of Attack Power plus </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'> of your level, <br /> and its CritStrike Bonus is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>.<br /> All targets affected by </span><span style='color:#11ff11'>Perpetual Loneliness</span><span style='color:#ffffff'> <br /> take damage over </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> giâys <br /> equal to </span><span style='color:#ffcb4a'>%d</span><span style='color:#ffffff'> per rank.<br /> </span><span style='color:#11ff11'>Dawn's End</span><span style='color:#ffffff'>'s flat damage bonus <br /> is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff'>, and its <br /> CritStrike Bonus is increased by </span><span style='color:#ffcb4a'>%d%%</span><span style='color:#ffffff;'>.</span>",
    },
};
